export const COMPARE_SFX = [
  "assets/sfx/15 Quick A.wav",
  "assets/sfx/15 Quick B.wav.wav",
  "assets/sfx/Camera Shutter 1A - \u0027Crunch\u0027 Click (-15 db) - Submitted by Ivan Khan.mp3",
  "assets/sfx/camera-shutter-6305.mp3",
  "assets/sfx/Cash Register (Kaching) - Sound Effect (HD).mp3",
  "assets/sfx/clean-fast-swooshaiff-14784.mp3",
  "assets/sfx/Click - Sound Effect (HD).mp3",
  "assets/sfx/gear sound effect.wav",
  "assets/sfx/Gears 1.wav",
  "assets/sfx/glitch 1.mp3",
  "assets/sfx/IPhone Notification Sound Spam.mp3",
  "assets/sfx/Jet Woosh.wav",
  "assets/sfx/keyboard 1.mp3",
  "assets/sfx/mouse click.mp3",
  "assets/sfx/Paper_Sound_Effects(128k).mp3",
  "assets/sfx/punch-Impacful.mp3",
  "assets/sfx/Riser SFX.mp3",
  "assets/sfx/whoosh-blow-flutter-shortwav-14678.mp3",
  "assets/sfx/wrong answer.mp3",
] as const;

