// lib/captions/styleSystems.ts
// 10 Distinct Professional Motion Caption Style Design Systems ($49+ tier)

import type { StyleSystemPreset } from './types';

export const STYLE_SYSTEMS: Record<string, StyleSystemPreset> = {
  'dynamic-punch': {
    id: 'dynamic-punch',
    name: 'Dynamic Punch',
    category: 'viral',
    description: 'High-energy viral kinetic pop with 3D red stroke bevels and cyan shock bursts.',
    defaultTypography: {
      heroFont: 'Impact, "Cabinet Grotesk", sans-serif',
      leadFont: 'Montserrat, "Plus Jakarta Sans", sans-serif',
      heroWeight: 900,
      leadWeight: 800,
      letterSpacingEm: 0.02,
      lineHeight: 1.05,
      textTransform: 'uppercase',
    },
    defaultMotion: {
      family: 'kinetic-slam',
      mass: 0.38,
      damping: 11,
      stiffness: 300,
      scaleEntrance: [1.38, 1.0],
      translateYEntrancePx: [18, 0],
      blurEntrancePx: [4, 0],
      exitStyle: 'whip-up',
      exitDurationFrames: 5,
      wordStaggerFrames: 2,
    },
    defaultEffects: {
      stylePreset: 'dynamic-punch',
      textColor: '#FFFFFF',
      highlightColor: '#FEE222',
      accentColor: '#FF2A54',
      textShadow: '0 4px 0 #7F1D1D, 0 8px 16px rgba(0,0,0,0.6)',
      textStroke: '3px #000000',
    },
    defaultLayout: {
      anchor: 'bottom-center',
      verticalOffsetPct: 74,
      maxLineWidthPx: 920,
      lineDistribution: 'single-line',
      safeMarginBottomPct: 22,
      textAlign: 'center',
    },
  },

  'studio-clean': {
    id: 'studio-clean',
    name: 'Studio Clean',
    category: 'saas',
    description: 'Stacked dark glassmorphism card with high-fashion tracking and electric yellow highlight.',
    defaultTypography: {
      heroFont: 'Inter, "Plus Jakarta Sans", sans-serif',
      leadFont: 'Inter, "Plus Jakarta Sans", sans-serif',
      heroWeight: 850,
      leadWeight: 600,
      letterSpacingEm: 0.01,
      lineHeight: 1.15,
      textTransform: 'none',
    },
    defaultMotion: {
      family: 'elastic-pop',
      mass: 0.45,
      damping: 14,
      stiffness: 240,
      scaleEntrance: [0.95, 1.0],
      translateYEntrancePx: [12, 0],
      blurEntrancePx: [6, 0],
      exitStyle: 'fade-out',
      exitDurationFrames: 5,
    },
    defaultEffects: {
      stylePreset: 'studio-clean',
      textColor: '#F8FAFC',
      highlightColor: '#FACC15',
      accentColor: '#38BDF8',
      textShadow: '0 2px 8px rgba(0,0,0,0.4)',
      containerBackground: 'rgba(15, 23, 42, 0.88)',
      containerBorder: '1px solid rgba(255, 255, 255, 0.12)',
      containerBackdropBlurPx: 12,
      badgePadding: '16px 32px',
      badgeRadiusPx: 20,
    },
    defaultLayout: {
      anchor: 'bottom-center',
      verticalOffsetPct: 74,
      maxLineWidthPx: 880,
      lineDistribution: 'balanced-2line',
      safeMarginBottomPct: 22,
      textAlign: 'center',
    },
  },

  'karaoke-pro': {
    id: 'karaoke-pro',
    name: 'Karaoke Pro',
    category: 'viral',
    description: 'Continuous smooth gradient text fill locked to exact speech duration with subpixel glowing edges.',
    defaultTypography: {
      heroFont: 'Inter, "Plus Jakarta Sans", sans-serif',
      leadFont: 'Inter, "Plus Jakarta Sans", sans-serif',
      heroWeight: 900,
      leadWeight: 800,
      letterSpacingEm: 0,
      lineHeight: 1.12,
      textTransform: 'uppercase',
    },
    defaultMotion: {
      family: 'smooth-fade',
      mass: 0.5,
      damping: 15,
      stiffness: 220,
      scaleEntrance: [0.96, 1.0],
      translateYEntrancePx: [10, 0],
      blurEntrancePx: [4, 0],
      exitStyle: 'fade-out',
      exitDurationFrames: 5,
    },
    defaultEffects: {
      stylePreset: 'karaoke-pro',
      textColor: 'rgba(255, 255, 255, 0.4)',
      highlightColor: '#00F0FF',
      accentColor: '#FF0055',
      textShadow: '0 2px 10px rgba(0,0,0,0.7)',
      containerBackground: 'rgba(0, 0, 0, 0.65)',
      containerBackdropBlurPx: 8,
      badgePadding: '14px 28px',
      badgeRadiusPx: 16,
    },
    defaultLayout: {
      anchor: 'bottom-center',
      verticalOffsetPct: 74,
      maxLineWidthPx: 940,
      lineDistribution: 'single-line',
      safeMarginBottomPct: 22,
      textAlign: 'center',
    },
  },

  'neon-kinetic': {
    id: 'neon-kinetic',
    name: 'Neon Kinetic',
    category: 'cyber',
    description: 'Cyberpunk dual cyan/magenta glow with subpixel entry jitter and pulse reactions.',
    defaultTypography: {
      heroFont: 'Montserrat, "Cabinet Grotesk", sans-serif',
      leadFont: 'Inter, sans-serif',
      heroWeight: 900,
      leadWeight: 700,
      letterSpacingEm: 0.04,
      lineHeight: 1.1,
      textTransform: 'uppercase',
    },
    defaultMotion: {
      family: 'cyber-glitch',
      mass: 0.35,
      damping: 13,
      stiffness: 340,
      scaleEntrance: [1.14, 1.0],
      translateYEntrancePx: [0, 0],
      blurEntrancePx: [4, 0],
      exitStyle: 'fade-out',
      exitDurationFrames: 4,
      glitchJitter: true,
      wordStaggerFrames: 1,
    },
    defaultEffects: {
      stylePreset: 'neon-kinetic',
      textColor: '#E0F2FE',
      highlightColor: '#00F0FF',
      accentColor: '#FF007F',
      textShadow: '0 0 10px #00F0FF, 0 0 25px #00F0FF88, 0 0 45px #FF007F55',
    },
    defaultLayout: {
      anchor: 'bottom-center',
      verticalOffsetPct: 74,
      maxLineWidthPx: 900,
      lineDistribution: 'single-line',
      safeMarginBottomPct: 22,
      textAlign: 'center',
    },
  },

  'dubai-gold': {
    id: 'dubai-gold',
    name: 'Dubai Gold',
    category: 'luxury',
    description: '24k gold metallic shimmer with architectural serif font pairing and soft champagne lighting.',
    defaultTypography: {
      heroFont: 'Cinzel, "Playfair Display", serif',
      leadFont: 'Montserrat, "Plus Jakarta Sans", sans-serif',
      heroWeight: 800,
      leadWeight: 600,
      letterSpacingEm: 0.06,
      lineHeight: 1.2,
      textTransform: 'uppercase',
    },
    defaultMotion: {
      family: 'shimmer-drift',
      mass: 0.65,
      damping: 18,
      stiffness: 160,
      scaleEntrance: [0.94, 1.0],
      translateYEntrancePx: [14, 0],
      blurEntrancePx: [6, 0],
      exitStyle: 'fade-out',
      exitDurationFrames: 6,
    },
    defaultEffects: {
      stylePreset: 'dubai-gold',
      textColor: '#FFFFFF',
      highlightColor: '#FFD700',
      accentColor: '#D4AF37',
      gradient: 'linear-gradient(135deg, #FFF6D0 0%, #FFD700 50%, #C89600 100%)',
      textShadow: '0 2px 14px rgba(212, 175, 55, 0.45), 0 4px 10px rgba(0,0,0,0.8)',
      containerBackground: 'rgba(10, 10, 12, 0.85)',
      containerBorder: '1px solid rgba(212, 175, 55, 0.35)',
      containerBackdropBlurPx: 10,
      badgePadding: '14px 30px',
      badgeRadiusPx: 18,
    },
    defaultLayout: {
      anchor: 'bottom-center',
      verticalOffsetPct: 74,
      maxLineWidthPx: 860,
      lineDistribution: 'balanced-2line',
      safeMarginBottomPct: 22,
      textAlign: 'center',
    },
  },

  'paper-collage': {
    id: 'paper-collage',
    name: 'Paper Collage',
    category: 'tactile',
    description: 'Vox-style tactile yellow torn paper tape badge with dynamic rotation skew.',
    defaultTypography: {
      heroFont: 'Impact, "Cabinet Grotesk", sans-serif',
      leadFont: 'Inter, sans-serif',
      heroWeight: 900,
      leadWeight: 800,
      letterSpacingEm: 0.01,
      lineHeight: 1.08,
      textTransform: 'uppercase',
    },
    defaultMotion: {
      family: 'paper-stamp',
      mass: 0.55,
      damping: 12,
      stiffness: 260,
      scaleEntrance: [1.22, 1.0],
      translateYEntrancePx: [-16, 0],
      blurEntrancePx: [2, 0],
      exitStyle: 'scale-down',
      exitDurationFrames: 4,
    },
    defaultEffects: {
      stylePreset: 'paper-collage',
      textColor: '#111827',
      highlightColor: '#1E1B4B',
      accentColor: '#F59E0B',
      containerBackground: '#FDE047',
      containerBorder: '2px solid #000000',
      containerTiltDeg: -1.6,
      textShadow: 'none',
      badgePadding: '14px 28px',
      badgeRadiusPx: 6,
    },
    defaultLayout: {
      anchor: 'bottom-center',
      verticalOffsetPct: 74,
      maxLineWidthPx: 860,
      lineDistribution: 'single-line',
      safeMarginBottomPct: 22,
      textAlign: 'center',
    },
  },

  'prism-pro': {
    id: 'prism-pro',
    name: 'Prism Pro',
    category: 'saas',
    description: 'Silicon Valley SaaS frosted glass card with glowing cyan-indigo gradient border.',
    defaultTypography: {
      heroFont: 'Inter, "Plus Jakarta Sans", sans-serif',
      leadFont: 'Inter, "Plus Jakarta Sans", sans-serif',
      heroWeight: 800,
      leadWeight: 600,
      letterSpacingEm: 0,
      lineHeight: 1.15,
      textTransform: 'none',
    },
    defaultMotion: {
      family: 'editorial-rise',
      mass: 0.5,
      damping: 16,
      stiffness: 200,
      scaleEntrance: [0.97, 1.0],
      translateYEntrancePx: [16, 0],
      blurEntrancePx: [6, 0],
      exitStyle: 'fade-out',
      exitDurationFrames: 5,
    },
    defaultEffects: {
      stylePreset: 'prism-pro',
      textColor: '#FFFFFF',
      highlightColor: '#38BDF8',
      accentColor: '#818CF8',
      containerBackground: 'rgba(15, 23, 42, 0.75)',
      containerBorder: '1px solid rgba(56, 189, 248, 0.3)',
      containerBackdropBlurPx: 16,
      textShadow: '0 2px 10px rgba(0,0,0,0.5)',
      badgePadding: '16px 32px',
      badgeRadiusPx: 20,
    },
    defaultLayout: {
      anchor: 'bottom-center',
      verticalOffsetPct: 74,
      maxLineWidthPx: 880,
      lineDistribution: 'balanced-2line',
      safeMarginBottomPct: 22,
      textAlign: 'center',
    },
  },

  'minimal-editorial': {
    id: 'minimal-editorial',
    name: 'Minimal Editorial',
    category: 'editorial',
    description: 'Quiet luxury monochrome rise-fade with wide kerning and ultra-clean drop shadow.',
    defaultTypography: {
      heroFont: 'Inter, "Plus Jakarta Sans", sans-serif',
      leadFont: 'Inter, "Plus Jakarta Sans", sans-serif',
      heroWeight: 600,
      leadWeight: 450,
      letterSpacingEm: 0.03,
      lineHeight: 1.25,
      textTransform: 'none',
    },
    defaultMotion: {
      family: 'editorial-rise',
      mass: 0.7,
      damping: 20,
      stiffness: 150,
      scaleEntrance: [0.99, 1.0],
      translateYEntrancePx: [14, 0],
      blurEntrancePx: [6, 0],
      exitStyle: 'fade-out',
      exitDurationFrames: 6,
    },
    defaultEffects: {
      stylePreset: 'minimal-editorial',
      textColor: '#F8FAFC',
      highlightColor: '#FFFFFF',
      accentColor: '#94A3B8',
      textShadow: '0 2px 4px rgba(0,0,0,0.8), 0 0 12px rgba(0,0,0,0.6)',
    },
    defaultLayout: {
      anchor: 'bottom-center',
      verticalOffsetPct: 74,
      maxLineWidthPx: 820,
      lineDistribution: 'balanced-2line',
      safeMarginBottomPct: 22,
      textAlign: 'center',
    },
  },

  'marker-highlight': {
    id: 'marker-highlight',
    name: 'Marker Highlight',
    category: 'tactile',
    description: 'Organic angled highlighter stroke behind active words with heavy bold lettering.',
    defaultTypography: {
      heroFont: 'Montserrat, "Cabinet Grotesk", sans-serif',
      leadFont: 'Inter, sans-serif',
      heroWeight: 900,
      leadWeight: 800,
      letterSpacingEm: 0,
      lineHeight: 1.1,
      textTransform: 'none',
    },
    defaultMotion: {
      family: 'elastic-pop',
      mass: 0.45,
      damping: 13,
      stiffness: 280,
      scaleEntrance: [0.95, 1.0],
      translateYEntrancePx: [8, 0],
      blurEntrancePx: [3, 0],
      exitStyle: 'fade-out',
      exitDurationFrames: 4,
    },
    defaultEffects: {
      stylePreset: 'marker-highlight',
      textColor: '#FFFFFF',
      highlightColor: '#FDE047',
      accentColor: '#F59E0B',
      textShadow: '0 2px 6px rgba(0,0,0,0.8)',
    },
    defaultLayout: {
      anchor: 'bottom-center',
      verticalOffsetPct: 74,
      maxLineWidthPx: 900,
      lineDistribution: 'single-line',
      safeMarginBottomPct: 22,
      textAlign: 'center',
    },
  },

  'liquid-chrome': {
    id: 'liquid-chrome',
    name: 'Liquid Chrome',
    category: 'industrial',
    description: 'Heavy condensed sans with liquid silver metallic bevels and deep black drop shadows.',
    defaultTypography: {
      heroFont: 'Impact, "Cabinet Grotesk", sans-serif',
      leadFont: 'Montserrat, sans-serif',
      heroWeight: 900,
      leadWeight: 800,
      letterSpacingEm: 0.03,
      lineHeight: 1.05,
      textTransform: 'uppercase',
    },
    defaultMotion: {
      family: 'kinetic-slam',
      mass: 0.42,
      damping: 12,
      stiffness: 290,
      scaleEntrance: [1.3, 1.0],
      translateYEntrancePx: [16, 0],
      blurEntrancePx: [5, 0],
      exitStyle: 'whip-up',
      exitDurationFrames: 5,
    },
    defaultEffects: {
      stylePreset: 'liquid-chrome',
      textColor: '#E2E8F0',
      highlightColor: '#38BDF8',
      accentColor: '#94A3B8',
      gradient: 'linear-gradient(180deg, #FFFFFF 0%, #CBD5E1 50%, #64748B 100%)',
      textShadow: '0 3px 0 #0F172A, 0 8px 20px rgba(0,0,0,0.8)',
      textStroke: '2px rgba(255,255,255,0.4)',
    },
    defaultLayout: {
      anchor: 'bottom-center',
      verticalOffsetPct: 74,
      maxLineWidthPx: 920,
      lineDistribution: 'single-line',
      safeMarginBottomPct: 22,
      textAlign: 'center',
    },
  },
};

/**
 * Normalizes any legacy or custom style string into one of the 10 core Style Systems
 */
export function resolveStyleSystem(styleName?: string): StyleSystemPreset {
  if (!styleName) return STYLE_SYSTEMS['dynamic-punch'];

  const normalized = styleName.toLowerCase().replace(/[_\s-]+/g, '-');

  if (STYLE_SYSTEMS[normalized]) {
    return STYLE_SYSTEMS[normalized];
  }

  // Alias mapping for legacy presets
  const ALIAS_MAP: Record<string, string> = {
    'studio-clean': 'studio-clean',
    'karaoke': 'karaoke-pro',
    'karaoke-fill': 'karaoke-pro',
    'shorts-karaoke': 'karaoke-pro',
    'neon': 'neon-kinetic',
    'arctic-glow': 'neon-kinetic',
    'neon-pulse': 'neon-kinetic',
    'gold-pill': 'dubai-gold',
    'vollkorn': 'dubai-gold',
    'cinematic': 'minimal-editorial',
    'reels-clean': 'minimal-editorial',
    'floating-serif': 'minimal-editorial',
    'minimal-fade': 'minimal-editorial',
    'bold-highlight-strip': 'paper-collage',
    'shatter': 'dynamic-punch',
    'pill-bounce': 'studio-clean',
    'pop-candy': 'studio-clean',
    'box': 'studio-clean',
    'split-color': 'studio-clean',
    'one-word': 'dynamic-punch',
    'big-bold': 'dynamic-punch',
    'bold-fire': 'dynamic-punch',
    'hustle': 'dynamic-punch',
    'bold-outline': 'dynamic-punch',
    'typewriter': 'prism-pro',
    'typewriter-code': 'prism-pro',
    'marker-highlight': 'marker-highlight',
    'metallic-gradient': 'liquid-chrome',
    'silver-chrome': 'liquid-chrome',
    'gradient-wave': 'neon-kinetic',
    'retro-vhs': 'paper-collage',
    'handwritten': 'marker-highlight',
    'glass-blur': 'prism-pro',
    'eclipse': 'studio-clean',
    'marigold': 'dubai-gold',
    'midnight': 'studio-clean',
  };

  const matchedKey = ALIAS_MAP[normalized] || 'dynamic-punch';
  return STYLE_SYSTEMS[matchedKey] || STYLE_SYSTEMS['dynamic-punch'];
}
