'use client';

import React, { useState, useEffect } from 'react';
import {
  AlertCircle,
  RotateCcw,
  Download,
  Copy,
  Check,
  Sparkles,
  Film,
  Info,
  Clock,
  Volume2,
  VolumeX,
  Mic,
  ChevronDown,
  ChevronUp,
  X,
} from 'lucide-react';

export type Mode = string;

export interface JobStatus {
  state: 'idle' | 'uploading' | 'starting' | 'rendering' | 'ready' | 'error';
  message: string;
  progress?: number;
  outputFile?: string;
  jobId?: string;
  title?: string;
  error?: string;
  diagnostics?: string[];
  clips?: Array<{
    renderId: string;
    title: string;
    status: 'rendering' | 'done' | 'failed';
    outputUrl?: string;
    error?: string;
    startSeconds?: number;
    endSeconds?: number;
    durationSeconds?: number;
    outputFile?: string;
  }>;
}

interface InteractiveRenderEngineProps {
  mode: Mode;
  status: JobStatus;
  title: string;
  fileName?: string;
  onRetry: () => void;
  onReset: () => void;
}

export default function InteractiveRenderEngine({
  mode,
  status,
  title,
  fileName,
  onRetry,
  onReset,
}: InteractiveRenderEngineProps) {
  const [copiedTitle, setCopiedTitle] = useState(false);
  const [copiedDesc, setCopiedDesc] = useState(false);
  const [soundEnabled, setSoundEnabled] = useState(true);
  const [showSpecs, setShowSpecs] = useState(false);
  const [showSocialCopy, setShowSocialCopy] = useState(false);

  const isFailed = status.state === 'error';
  const isReady = status.state === 'ready' || Boolean(status.outputFile);

  // Raw progress calculation (handles fractional progress 0.0-1.0 and whole numbers 0-100)
  const rawProgress = isReady
    ? 100
    : typeof status.progress === 'number'
    ? (status.progress > 0 && status.progress <= 1 ? status.progress * 100 : status.progress)
    : (
      status.state === 'uploading' ? 15 :
      status.state === 'starting' ? 35 :
      status.state === 'rendering' ? 70 : 0
    );
  const percentage = Math.min(100, Math.max(0, Math.round(rawProgress)));

  // Compact 4 Steps for Horizontal Stepper
  const steps = mode === 'audioClean'
    ? [
        { shortLabel: 'Script', label: 'Transcribing speech & script', doneAt: 25 },
        { shortLabel: 'Retakes', label: 'Detecting retakes & mistakes', doneAt: 50 },
        { shortLabel: 'Mastering', label: 'Normalizing loudness & noise', doneAt: 75 },
        { shortLabel: 'Export', label: 'Exporting studio clean MP3', doneAt: 100 },
      ]
    : [
        { shortLabel: 'Project', label: 'Preparing project', doneAt: 15 },
        { shortLabel: 'Assets', label: 'Processing assets', doneAt: 40 },
        { shortLabel: 'Effects', label: 'Applying animation & captions', doneAt: 75 },
        { shortLabel: 'Render', label: 'Rendering 30 FPS MP4 video', doneAt: 100 },
      ];

  // Current active step
  const activeStepIndex = isReady
    ? steps.length - 1
    : Math.min(
        steps.length - 1,
        steps.findIndex((s) => percentage < s.doneAt) !== -1
          ? steps.findIndex((s) => percentage < s.doneAt)
          : 0
      );

  // Dynamic project display title
  const displayTitle = title && title.length > 3 && title.toLowerCase() !== 'ai'
    ? title
    : fileName && fileName.length > 3
    ? fileName
    : 'Viral Reel Project';

  // Auto-generated viral description & hashtags for social posting
  const autoGeneratedDesc = `${displayTitle} 🚀 ${mode === 'audioClean' ? 'Mastered with ItnaVideo AI Studio (EBU R128 Broadcast Loudness, noise filtered).' : 'Created automatically with ItnaVideo AI Studio.'}\n\n#audio #voiceover #podcast #creator #itnavideo`;

  // Estimate remaining time
  const secondsRemaining = Math.max(0, Math.round(((100 - percentage) / 100) * 85));
  const formatTimeRemaining = (secs: number) => {
    if (secs <= 0) return 'Almost ready...';
    const mins = Math.floor(secs / 60);
    const s = secs % 60;
    return mins > 0 ? `${mins}m ${s}s` : `${s}s`;
  };

  const handleCopyTitle = () => {
    navigator.clipboard.writeText(displayTitle);
    setCopiedTitle(true);
    setTimeout(() => setCopiedTitle(false), 2000);
  };

  const handleCopyDesc = () => {
    navigator.clipboard.writeText(autoGeneratedDesc);
    setCopiedDesc(true);
    setTimeout(() => setCopiedDesc(false), 2000);
  };

  // Play audio Chime when ready
  useEffect(() => {
    if (isReady && soundEnabled) {
      try {
        const audioCtx = new (window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext)();
        const osc = audioCtx.createOscillator();
        const gain = audioCtx.createGain();
        osc.type = 'sine';
        osc.frequency.setValueAtTime(523.25, audioCtx.currentTime);
        osc.frequency.exponentialRampToValueAtTime(659.25, audioCtx.currentTime + 0.15);
        gain.gain.setValueAtTime(0.12, audioCtx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.35);
        osc.connect(gain);
        gain.connect(audioCtx.destination);
        osc.start();
        osc.stop(audioCtx.currentTime + 0.35);
      } catch {
        // Audio autoplay blocked
      }
    }
  }, [isReady, soundEnabled]);

  return (
    <div className="relative w-full max-w-2xl mx-auto rounded-3xl border border-white/10 bg-zinc-950/95 p-4 sm:p-6 text-white shadow-2xl space-y-4 font-sans select-none backdrop-blur-xl">

      {/* ── M3 TOP APP BAR ── */}
      <div className="flex items-center justify-between border-b border-white/10 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center font-black text-slate-950 text-xs shadow-md">
            {mode === 'audioClean' ? <Mic size={14} /> : <Film size={14} />}
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-extrabold text-sm text-white tracking-tight">ItnaVideo Studio</span>
              <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${
                isReady
                  ? 'text-emerald-400 bg-emerald-950/60 border-emerald-800/60'
                  : 'text-amber-300 bg-amber-950/60 border-amber-800/60'
              }`}>
                {isReady ? 'Ready' : 'Rendering · 30 FPS'}
              </span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-1.5">
          <button
            onClick={() => setSoundEnabled(!soundEnabled)}
            className="p-2 rounded-xl bg-zinc-900/80 border border-white/5 hover:bg-zinc-800 text-zinc-400 hover:text-white transition-colors"
            title={soundEnabled ? 'Mute chime' : 'Enable chime'}
          >
            {soundEnabled ? <Volume2 size={15} /> : <VolumeX size={15} />}
          </button>
          <button
            onClick={onReset}
            className="p-2 rounded-xl bg-zinc-900/80 hover:bg-zinc-800 border border-white/5 text-zinc-400 hover:text-white transition-colors"
            title="Close"
          >
            <X size={15} />
          </button>
        </div>
      </div>

      {/* ── M3 PREVIEW & STATUS CONTAINER ── */}
      <div className="relative w-full rounded-2xl bg-zinc-900/80 border border-white/10 overflow-hidden shadow-inner">
        {isReady && status.outputFile ? (
          mode === 'audioClean' ? (
            <div className="w-full flex flex-col items-center justify-center p-6 space-y-3 bg-gradient-to-b from-zinc-900 to-zinc-950">
              <div className="w-12 h-12 rounded-full bg-orange-500/20 border border-orange-500/40 text-orange-400 flex items-center justify-center shadow-lg">
                <Mic size={24} />
              </div>
              <div className="text-center">
                <p className="font-extrabold text-sm text-white">Audio Cleaned &amp; Mastered</p>
                <p className="text-xs text-zinc-400">Silences trimmed • EBU R128 loudness normalized</p>
              </div>
              <audio src={status.outputFile} controls autoPlay className="w-full max-w-md mt-2" />
            </div>
          ) : (
            <div className="relative w-full aspect-video max-h-[300px] bg-black flex items-center justify-center">
              <video
                src={status.outputFile}
                controls
                autoPlay
                playsInline
                className="w-full h-full object-contain"
              />
            </div>
          )
        ) : isFailed ? (
          <div className="p-6 text-center space-y-3">
            <div className="w-12 h-12 rounded-full bg-red-500/20 border border-red-500/40 text-red-400 mx-auto flex items-center justify-center">
              <AlertCircle size={24} />
            </div>
            <p className="font-bold text-sm text-red-300">Render Interrupted</p>
            <p className="text-xs text-zinc-400 max-w-sm mx-auto">{status.error || status.message || 'Error occurred.'}</p>
            {status.diagnostics && status.diagnostics.length > 0 ? (
              <details className="mt-2 text-left bg-zinc-950/90 rounded-xl p-2.5 border border-zinc-800 text-[10px] text-zinc-400 max-w-md mx-auto">
                <summary className="cursor-pointer font-mono font-bold text-zinc-300 select-none">Technical Details</summary>
                <div className="mt-1.5 space-y-1 font-mono break-all max-h-32 overflow-y-auto">
                  {status.diagnostics.map((d, i) => (
                    <div key={i}>{d}</div>
                  ))}
                </div>
              </details>
            ) : null}
            <button
              onClick={onRetry}
              className="px-5 py-2.5 bg-red-600 hover:bg-red-500 text-white rounded-xl font-bold text-xs transition-all inline-flex items-center gap-1.5 shadow-lg"
            >
              <RotateCcw size={14} />
              <span>Retry Render</span>
            </button>
          </div>
        ) : (
          /* M3 Waiting & Rendering State (Clean & Compact) */
          <div className="p-6 sm:p-8 flex flex-col items-center justify-center text-center space-y-4 bg-gradient-to-b from-zinc-900/90 via-zinc-900/50 to-zinc-950">
            {/* Shimmering Ambient Glow Pulse */}
            <div className="relative">
              <div className="w-16 h-16 rounded-full bg-gradient-to-tr from-amber-500/20 via-orange-500/20 to-teal-500/20 border border-amber-400/30 flex items-center justify-center text-amber-300 animate-pulse shadow-[0_0_30px_rgba(245,158,11,0.2)]">
                <Sparkles size={26} className="animate-spin" style={{ animationDuration: '6s' }} />
              </div>
            </div>

            <div className="space-y-1 max-w-sm">
              <p className="text-sm font-extrabold text-white tracking-wide truncate">{displayTitle}</p>
              <p className="text-xs text-amber-300/90 font-medium">
                {status.message || steps[activeStepIndex]?.label || 'Processing video scenes...'}
              </p>
            </div>

            {/* Time Remaining Pill */}
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-zinc-950/80 border border-white/10 text-[11px] font-bold text-zinc-300">
              <Clock size={12} className="text-amber-400" />
              <span>Est. time: {formatTimeRemaining(secondsRemaining)}</span>
              <span className="text-zinc-500">•</span>
              <span className="font-mono text-amber-400">{percentage}%</span>
            </div>
          </div>
        )}
      </div>

      {/* ── M3 LINEAR PROGRESS BAR ── */}
      {!isFailed && (
        <div className="space-y-1.5">
          <div className="flex items-center justify-between text-[11px] font-bold px-1">
            <span className="text-zinc-400">
              {isReady ? 'Render Finished ✓' : `Step ${activeStepIndex + 1} of 4: ${steps[activeStepIndex]?.label}`}
            </span>
            <span className="font-mono text-xs font-black text-amber-400">{percentage}%</span>
          </div>

          <div className="w-full h-2 bg-zinc-900 rounded-full overflow-hidden border border-white/5 p-0.5">
            <div
              className="h-full bg-gradient-to-r from-amber-500 via-orange-400 to-emerald-400 rounded-full transition-all duration-300 shadow-[0_0_12px_rgba(245,158,11,0.4)]"
              style={{ width: `${Math.max(4, percentage)}%` }}
            />
          </div>
        </div>
      )}

      {/* ── M3 COMPACT 4-STEP HORIZONTAL STEPPER (Replaces bulky vertical cards) ── */}
      {!isFailed && (
        <div className="grid grid-cols-4 gap-1.5 pt-1">
          {steps.map((step, idx) => {
            const isCompleted = percentage >= step.doneAt || isReady;
            const isCurrent = !isCompleted && idx === activeStepIndex;

            return (
              <div
                key={idx}
                className={`flex flex-col items-center justify-center p-2 rounded-xl border text-center transition-all ${
                  isCompleted
                    ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300'
                    : isCurrent
                    ? 'bg-amber-500/15 border-amber-400/50 text-amber-200 ring-1 ring-amber-400/30 shadow-sm'
                    : 'bg-zinc-900/40 border-white/5 text-zinc-500'
                }`}
              >
                <div className="flex items-center gap-1 mb-0.5">
                  <span
                    className={`w-4 h-4 rounded-full flex items-center justify-center text-[9px] font-black ${
                      isCompleted
                        ? 'bg-emerald-400 text-slate-950'
                        : isCurrent
                        ? 'bg-amber-400 text-slate-950 animate-pulse'
                        : 'bg-zinc-800 text-zinc-400'
                    }`}
                  >
                    {isCompleted ? <Check size={10} strokeWidth={3} /> : idx + 1}
                  </span>
                </div>
                <span className="text-[10px] font-bold leading-tight truncate w-full">
                  {step.shortLabel}
                </span>
              </div>
            );
          })}
        </div>
      )}

      {/* ── M3 ACTIONS AREA (WHEN READY) ── */}
      {isReady && status.outputFile ? (
        <div className="space-y-3 pt-2 animate-in fade-in duration-300">
          <a
            href={status.outputFile}
            download={mode === 'audioClean' ? 'itnavideo-clean-studio-audio.mp3' : `itnavideo-${mode || 'reel'}.mp4`}
            className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-amber-400 via-orange-400 to-emerald-400 hover:brightness-110 text-slate-950 font-black text-sm transition-all flex items-center justify-center gap-2 shadow-[0_0_24px_rgba(245,158,11,0.35)]"
          >
            <Download size={18} />
            <span>{mode === 'audioClean' ? 'Download Clean Audio (MP3)' : 'Download Ready Video (MP4)'}</span>
          </a>

          {/* Collapsible Social Title & Caption Accordion */}
          <div className="rounded-2xl border border-white/10 bg-zinc-900/60 overflow-hidden">
            <button
              onClick={() => setShowSocialCopy(!showSocialCopy)}
              className="w-full p-3.5 flex items-center justify-between text-xs font-bold text-zinc-300 hover:bg-white/[0.02] transition-colors"
            >
              <span className="flex items-center gap-2">
                <Sparkles size={14} className="text-amber-400" />
                Social Title &amp; Description
              </span>
              <div className="flex items-center gap-1.5 text-zinc-500">
                <span className="text-[10px] text-amber-400 bg-amber-950/60 px-2 py-0.5 rounded-full border border-amber-800/40">Ready to post</span>
                {showSocialCopy ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </div>
            </button>

            {showSocialCopy && (
              <div className="p-3.5 pt-0 space-y-3 border-t border-white/5">
                <div className="space-y-1">
                  <div className="flex items-center justify-between text-[11px] font-bold text-zinc-400">
                    <span>Title</span>
                    <button
                      onClick={handleCopyTitle}
                      className="text-amber-400 hover:text-amber-300 flex items-center gap-1 text-[10px]"
                    >
                      {copiedTitle ? <Check size={11} /> : <Copy size={11} />}
                      <span>{copiedTitle ? 'Copied' : 'Copy'}</span>
                    </button>
                  </div>
                  <div className="bg-zinc-950 border border-white/5 rounded-xl p-2.5 text-xs text-white font-medium truncate">
                    {displayTitle}
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="flex items-center justify-between text-[11px] font-bold text-zinc-400">
                    <span>Caption &amp; Hashtags</span>
                    <button
                      onClick={handleCopyDesc}
                      className="text-amber-400 hover:text-amber-300 flex items-center gap-1 text-[10px]"
                    >
                      {copiedDesc ? <Check size={11} /> : <Copy size={11} />}
                      <span>{copiedDesc ? 'Copied' : 'Copy'}</span>
                    </button>
                  </div>
                  <div className="bg-zinc-950 border border-white/5 rounded-xl p-2.5 text-xs text-zinc-300 leading-relaxed max-h-24 overflow-y-auto whitespace-pre-wrap font-sans">
                    {autoGeneratedDesc}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      ) : null}

      {/* ── OPTIONAL COLLAPSIBLE EXPORT SPECS (Clean, out of the way) ── */}
      <div className="pt-1">
        <button
          onClick={() => setShowSpecs(!showSpecs)}
          className="mx-auto flex items-center gap-1 text-[10px] font-bold text-zinc-500 hover:text-zinc-400 transition-colors"
        >
          <Info size={11} />
          <span>{showSpecs ? 'Hide video specs' : '1080p · 30 FPS · H.264 (Specs)'}</span>
          {showSpecs ? <ChevronUp size={11} /> : <ChevronDown size={11} />}
        </button>

        {showSpecs && (
          <div className="mt-2 p-3 rounded-2xl bg-zinc-900/60 border border-white/5 text-[11px] space-y-1.5">
            <div className="flex items-center justify-between text-zinc-400">
              <span>Resolution</span>
              <span className="font-mono text-white font-bold">1080p HD (1080x1920)</span>
            </div>
            <div className="flex items-center justify-between text-zinc-400">
              <span>Frame Rate</span>
              <span className="font-mono text-emerald-400 font-bold">30 FPS</span>
            </div>
            <div className="flex items-center justify-between text-zinc-400">
              <span>Encoding</span>
              <span className="font-mono text-white font-bold">MP4 (H.264 FastStart)</span>
            </div>
          </div>
        )}
      </div>

    </div>
  );
}
