'use client';

import React, { useState, useEffect } from 'react';
import {
  CheckCircle2,
  AlertCircle,
  RotateCcw,
  Download,
  Copy,
  Check,
  Sparkles,
  Film,
  Info,
  Clock,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Mic,
} from 'lucide-react';

export type Mode = string;

export interface JobStatus {
  state: 'idle' | 'uploading' | 'starting' | 'rendering' | 'ready' | 'error';
  message: string;
  progress?: number;
  outputFile?: string;
  jobId?: string;
  title?: string;
  error?: string;
  diagnostics?: string[];
  clips?: Array<{
    renderId: string;
    title: string;
    status: 'rendering' | 'done' | 'failed';
    outputUrl?: string;
    error?: string;
    startSeconds?: number;
    endSeconds?: number;
    durationSeconds?: number;
    outputFile?: string;
  }>;
}

interface InteractiveRenderEngineProps {
  mode: Mode;
  status: JobStatus;
  title: string;
  fileName?: string;
  onRetry: () => void;
  onReset: () => void;
}

export default function InteractiveRenderEngine({
  mode,
  status,
  title,
  fileName,
  onRetry,
  onReset,
}: InteractiveRenderEngineProps) {
  const [copiedTitle, setCopiedTitle] = useState(false);
  const [copiedDesc, setCopiedDesc] = useState(false);
  const [soundEnabled, setSoundEnabled] = useState(true);
  const [isPlayingPreview, setIsPlayingPreview] = useState(true);

  const isWorking = status.state === 'uploading' || status.state === 'starting' || status.state === 'rendering';
  const isFailed = status.state === 'error';
  const isReady = status.state === 'ready' || Boolean(status.outputFile);

  // Raw progress calculation (handles fractional progress 0.0-1.0 and whole numbers 0-100)
  const rawProgress = isReady
    ? 100
    : typeof status.progress === 'number'
    ? (status.progress > 0 && status.progress <= 1 ? status.progress * 100 : status.progress)
    : (
      status.state === 'uploading' ? 15 :
      status.state === 'starting' ? 35 :
      status.state === 'rendering' ? 70 : 0
    );
  const percentage = Math.min(100, Math.max(0, Math.round(rawProgress)));

  // 4 Simple Progress Steps matching the hand-drawn drawing:
  // 1. Preparing project
  // 2. Processing assets
  // 3. Applying animation
  // 4. Rendering final video
  const steps = mode === 'audioClean'
    ? [
        { label: 'Transcribing speech & script', doneAt: 25 },
        { label: 'Detecting retakes & mistakes', doneAt: 50 },
        { label: 'Normalizing loudness & silence', doneAt: 75 },
        { label: 'Exporting studio clean MP3', doneAt: 100 },
      ]
    : [
        { label: 'Preparing project', doneAt: 15 },
        { label: 'Processing assets', doneAt: 40 },
        { label: 'Applying animation', doneAt: 75 },
        { label: 'Rendering final video', doneAt: 100 },
      ];

  // Dynamic project display title
  const displayTitle = title && title.length > 3 && title.toLowerCase() !== 'ai'
    ? title
    : fileName && fileName.length > 3
    ? fileName
    : 'Viral Reel Project';

  // Auto-generated viral description & hashtags for social posting
  const autoGeneratedDesc = `${displayTitle} 🚀 ${mode === 'audioClean' ? 'Mastered with ItnaVideo AI Studio (EBU R128 Broadcast Loudness, noise filtered).' : 'Created automatically with ItnaVideo AI Studio.'}\n\n#audio #voiceover #podcast #creator #itnavideo`;

  // Estimate remaining time
  const secondsRemaining = Math.max(0, Math.round(((100 - percentage) / 100) * 85));
  const formatTimeRemaining = (secs: number) => {
    if (secs <= 0) return 'Almost ready...';
    const mins = Math.floor(secs / 60);
    const s = secs % 60;
    return mins > 0 ? `${mins}m ${s}s` : `${s}s`;
  };

  const handleCopyTitle = () => {
    navigator.clipboard.writeText(displayTitle);
    setCopiedTitle(true);
    setTimeout(() => setCopiedTitle(false), 2000);
  };

  const handleCopyDesc = () => {
    navigator.clipboard.writeText(autoGeneratedDesc);
    setCopiedDesc(true);
    setTimeout(() => setCopiedDesc(false), 2000);
  };

  // Play audio Chime when ready
  useEffect(() => {
    if (isReady && soundEnabled) {
      try {
        const audioCtx = new (window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext)();
        const osc = audioCtx.createOscillator();
        const gain = audioCtx.createGain();
        osc.type = 'sine';
        osc.frequency.setValueAtTime(523.25, audioCtx.currentTime);
        osc.frequency.exponentialRampToValueAtTime(659.25, audioCtx.currentTime + 0.15);
        gain.gain.setValueAtTime(0.12, audioCtx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + 0.35);
        osc.connect(gain);
        gain.connect(audioCtx.destination);
        osc.start();
        osc.stop(audioCtx.currentTime + 0.35);
      } catch {
        // Audio autoplay blocked
      }
    }
  }, [isReady, soundEnabled]);

  return (
    <div className="relative w-full rounded-3xl border border-zinc-800 bg-zinc-950 p-5 sm:p-7 text-white shadow-2xl space-y-6 font-sans select-none">
      
      {/* ── TOP HEADER BAR matching sketch ($1.5 credit / 1 Credit Used) ── */}
      <div className="flex items-center justify-between border-b border-zinc-800/80 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-emerald-400 to-teal-600 flex items-center justify-center font-black text-slate-950 shadow-md">
            IT
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-extrabold text-base text-white tracking-tight">ItnaVideo Studio</span>
              <span className="text-[10px] font-extrabold text-emerald-400 bg-emerald-950/80 border border-emerald-800/60 px-2 py-0.5 rounded-full uppercase tracking-wider">
                1 Credit Used
              </span>
            </div>
            <p className="text-xs text-zinc-400">
              {mode === 'audioClean' ? 'AI Voiceover Cleaner & Audio Mastering Engine' : 'Simple & Fast HD Video Export Engine'}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setSoundEnabled(!soundEnabled)}
            className="p-2 rounded-xl bg-zinc-900 border border-zinc-800 hover:bg-zinc-800 text-zinc-400 hover:text-white transition-colors"
            title={soundEnabled ? 'Mute chimes' : 'Enable chimes'}
          >
            {soundEnabled ? <Volume2 size={16} /> : <VolumeX size={16} />}
          </button>

          {isReady && status.outputFile ? (
            <a
              href={status.outputFile}
              download={mode === 'audioClean' ? 'cleaned-voiceover.mp3' : `itnavideo-${mode || 'reel'}.mp4`}
              className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-emerald-400 to-teal-300 hover:from-emerald-300 hover:to-teal-200 text-slate-950 font-black text-xs transition-all flex items-center gap-2 shadow-[0_0_20px_rgba(16,185,129,0.3)] hover:scale-102"
            >
              <Download size={15} />
              <span>{mode === 'audioClean' ? 'Download Clean Audio (.mp3)' : 'Download MP4 Video'}</span>
            </a>
          ) : (
            <button
              onClick={onReset}
              className="px-4 py-2 rounded-xl bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-zinc-300 text-xs font-bold transition-colors"
            >
              Close
            </button>
          )}
        </div>
      </div>

      {/* ── MAIN 2-COLUMN GRID (Matching Sketch Layout) ── */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">

        {/* LEFT COLUMN: VIDEO PREVIEW & PROGRESS STEPS (7 COLS) */}
        <div className="lg:col-span-7 bg-zinc-900/60 rounded-2xl border border-zinc-800/80 p-5 space-y-5 shadow-xl">
          <div className="flex items-center justify-between">
            <h3 className="font-extrabold text-sm text-white flex items-center gap-2">
              {mode === 'audioClean' ? (
                <>
                  <Mic size={16} className="text-orange-400" />
                  Cleaning Your Audio
                </>
              ) : (
                <>
                  <Film size={16} className="text-emerald-400" />
                  Rendering Your Video
                </>
              )}
            </h3>
            <span className="text-xs font-mono text-emerald-400 bg-emerald-950/80 px-2.5 py-1 rounded-lg border border-emerald-800/50">
              {isReady ? '100% Ready' : `${percentage}% Completed`}
            </span>
          </div>

          {/* VIDEO / AUDIO PLAYER PREVIEW BOX */}
          <div className={`relative w-full ${mode === 'audioClean' ? 'h-64' : 'aspect-[9/16] max-h-[420px]'} mx-auto rounded-2xl bg-zinc-950 border-2 border-zinc-800 overflow-hidden flex items-center justify-center shadow-2xl`}>
            {isReady && status.outputFile ? (
              mode === 'audioClean' ? (
                <div className="w-full h-full flex flex-col items-center justify-center p-6 space-y-4 bg-gradient-to-b from-zinc-900 to-zinc-950">
                  <div className="w-14 h-14 rounded-full bg-orange-500/20 border border-orange-500/40 text-orange-400 flex items-center justify-center shadow-lg">
                    <Mic size={28} />
                  </div>
                  <div className="text-center">
                    <p className="font-extrabold text-sm text-white">Audio Cleaned & Normalized</p>
                    <p className="text-xs text-zinc-400 mt-0.5">Retakes & long silences removed • Consistent studio loudness</p>
                  </div>
                  <audio
                    src={status.outputFile}
                    controls
                    autoPlay
                    className="w-full max-w-sm mt-1"
                  />
                </div>
              ) : (
                <video
                  src={status.outputFile}
                  controls
                  autoPlay
                  playsInline
                  className="w-full h-full object-contain"
                />
              )
            ) : isFailed ? (
              <div className="p-6 text-center space-y-3">
                <div className="w-12 h-12 rounded-full bg-red-500/20 border border-red-500/40 text-red-400 mx-auto flex items-center justify-center">
                  <AlertCircle size={24} />
                </div>
                <p className="font-bold text-sm text-red-300">Render Interrupted</p>
                <p className="text-xs text-zinc-400 max-w-xs">{status.error || status.message || 'Error occurred.'}</p>
                <button
                  onClick={onRetry}
                  className="px-4 py-2 bg-red-600 hover:bg-red-500 text-white rounded-xl font-bold text-xs transition-all inline-flex items-center gap-1.5"
                >
                  <RotateCcw size={14} />
                  <span>Retry Render</span>
                </button>
              </div>
            ) : (
              /* Animated Render Canvas */
              <div className="relative w-full h-full flex flex-col justify-between p-5 bg-gradient-to-b from-zinc-900/90 to-zinc-950">
                <div className="flex justify-between items-center text-[11px] font-bold text-zinc-400">
                  <span className="flex items-center gap-1.5 text-emerald-400 bg-emerald-950/80 px-2.5 py-0.5 rounded-full border border-emerald-800/50">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-ping" />
                    Rendering HD Video
                  </span>
                  <span className="font-mono">1080p · 60 FPS</span>
                </div>

                <div className="my-auto text-center space-y-3">
                  <div className="w-14 h-14 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 mx-auto flex items-center justify-center animate-spin">
                    <Sparkles size={24} />
                  </div>
                  <div className="space-y-1">
                    <p className="text-sm font-black text-white uppercase tracking-wider">{displayTitle}</p>
                    <p className="text-xs text-emerald-400 font-medium">{status.message || 'Applying 3D typography & scenes...'}</p>
                  </div>
                </div>

                <div className="flex items-center justify-between text-xs font-bold text-zinc-400 bg-zinc-900/90 p-2 rounded-xl border border-zinc-800">
                  <span className="flex items-center gap-1 text-emerald-400">
                    <Clock size={13} />
                    Est. Time: {formatTimeRemaining(secondsRemaining)}
                  </span>
                  <span className="font-mono text-zinc-300">{percentage}%</span>
                </div>
              </div>
            )}
          </div>

          {/* PROGRESS & ESTIMATED TIME BAR (Matching Sketch: Progress — 1m 25sec  68%) */}
          <div className="space-y-2 pt-2 border-t border-zinc-800">
            <div className="flex items-center justify-between text-xs font-bold">
              <span className="text-zinc-300 flex items-center gap-1.5">
                <Clock size={14} className="text-emerald-400" />
                Progress — {isReady ? 'Finished' : formatTimeRemaining(secondsRemaining)}
              </span>
              <span className="font-mono font-black text-emerald-400 text-sm">{percentage}%</span>
            </div>

            {/* Smooth Gradient Progress Track */}
            <div className="w-full h-3 bg-zinc-950 rounded-full overflow-hidden border border-zinc-800 p-0.5">
              <div
                className="h-full bg-gradient-to-r from-emerald-500 via-teal-400 to-cyan-400 rounded-full transition-all duration-300 shadow-[0_0_12px_rgba(16,185,129,0.5)]"
                style={{ width: `${Math.max(4, percentage)}%` }}
              />
            </div>
          </div>

          {/* 4 SIMPLE SEQUENTIAL STEPS (Matching Hand-Drawn Sketch) */}
          <div className="space-y-2 pt-2">
            {steps.map((step, idx) => {
              const isCompleted = percentage >= step.doneAt || isReady;
              const isCurrent = !isCompleted && (idx === 0 || percentage >= steps[idx - 1].doneAt);

              return (
                <div
                  key={idx}
                  className={`flex items-center justify-between p-3 rounded-xl border text-xs font-semibold transition-all ${
                    isCompleted
                      ? 'bg-emerald-950/40 border-emerald-500/40 text-emerald-300'
                      : isCurrent
                      ? 'bg-zinc-900 border-amber-500/60 text-amber-200 ring-1 ring-amber-500/40'
                      : 'bg-zinc-950/50 border-zinc-800/80 text-zinc-500'
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <div
                      className={`w-6 h-6 rounded-full flex items-center justify-center font-extrabold text-[11px] ${
                        isCompleted
                          ? 'bg-emerald-500 text-slate-950'
                          : isCurrent
                          ? 'bg-amber-400 text-slate-950 animate-pulse'
                          : 'bg-zinc-800 text-zinc-400'
                      }`}
                    >
                      {isCompleted ? <Check size={13} strokeWidth={3} /> : idx + 1}
                    </div>
                    <span>{step.label}</span>
                  </div>

                  <span className="font-mono text-[10px] uppercase">
                    {isCompleted ? 'Done ✓' : isCurrent ? 'Processing...' : 'Waiting'}
                  </span>
                </div>
              );
            })}
          </div>
        </div>

        {/* RIGHT COLUMN: RENDER DETAILS & AUTO METADATA (5 COLS) */}
        <div className="lg:col-span-5 space-y-5">
          
          {/* 1. RENDER DETAILS BOX (Matching Sketch: Resolution, Format, Frame Rate, Video Size, Quality) */}
          <div className="bg-zinc-900/80 rounded-2xl border border-zinc-800/80 p-5 space-y-4 shadow-xl">
            <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
              <h4 className="font-extrabold text-xs text-white uppercase tracking-wider flex items-center gap-1.5">
                <Info size={14} className={mode === 'audioClean' ? "text-orange-400" : "text-emerald-400"} />
                {mode === 'audioClean' ? 'Audio Export Specs' : 'Render Details'}
              </h4>
              <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${mode === 'audioClean' ? 'text-orange-400 bg-orange-950 border-orange-800/60' : 'text-emerald-400 bg-emerald-950 border-emerald-800/60'}`}>
                {mode === 'audioClean' ? 'Studio Quality' : 'HD Quality'}
              </span>
            </div>

            {mode === 'audioClean' ? (
              <div className="space-y-2.5 text-xs">
                <div className="flex items-center justify-between py-1 border-b border-zinc-800/60">
                  <span className="text-zinc-400 font-medium">Format</span>
                  <span className="font-mono font-bold text-emerald-400">MP3 (libmp3lame)</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-zinc-800/60">
                  <span className="text-zinc-400 font-medium">Bitrate</span>
                  <span className="font-mono font-bold text-white">192 kbps CBR</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-zinc-800/60">
                  <span className="text-zinc-400 font-medium">Sample Rate</span>
                  <span className="font-mono font-bold text-purple-300">44.1 kHz Studio</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-zinc-800/60">
                  <span className="text-zinc-400 font-medium">Volume Normalization</span>
                  <span className="font-mono font-bold text-amber-300">EBU R128 (-16 LUFS)</span>
                </div>
                <div className="flex items-center justify-between py-1">
                  <span className="text-zinc-400 font-medium">Noise Filter</span>
                  <span className="font-bold text-emerald-400">Spectral De-noise</span>
                </div>
              </div>
            ) : (
              <div className="space-y-2.5 text-xs">
                <div className="flex items-center justify-between py-1 border-b border-zinc-800/60">
                  <span className="text-zinc-400 font-medium">Resolution</span>
                  <span className="font-mono font-bold text-white">1080p (1920x1080)</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-zinc-800/60">
                  <span className="text-zinc-400 font-medium">Format</span>
                  <span className="font-mono font-bold text-emerald-400">MP4 (H.264)</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-zinc-800/60">
                  <span className="text-zinc-400 font-medium">Frame Rate</span>
                  <span className="font-mono font-bold text-white">60 FPS</span>
                </div>
                <div className="flex items-center justify-between py-1 border-b border-zinc-800/60">
                  <span className="text-zinc-400 font-medium">Video Size</span>
                  <span className="font-mono font-bold text-purple-300">~8.5 MB</span>
                </div>
                <div className="flex items-center justify-between py-1">
                  <span className="text-zinc-400 font-medium">Quality</span>
                  <span className="font-bold text-amber-300">1080p HD Ultra</span>
                </div>
              </div>
            )}
          </div>

          {/* 2. AUTO-GENERATED TITLE & DESCRIPTION BOX (Matching Sketch) */}
          <div className="bg-zinc-900/80 rounded-2xl border border-zinc-800/80 p-5 space-y-4 shadow-xl">
            <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
              <h4 className="font-extrabold text-xs text-white uppercase tracking-wider flex items-center gap-1.5">
                <Sparkles size={14} className="text-amber-400" />
                Generated Title &amp; Description
              </h4>
              <span className="text-[10px] font-bold text-amber-400 bg-amber-950 px-2 py-0.5 rounded-full border border-amber-800/60">
                Ready for Social
              </span>
            </div>

            {/* Generated Title Field */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between text-[11px] font-bold text-zinc-300">
                <span>{mode === 'audioClean' ? 'Audio Title' : 'Video Title'}</span>
                <button
                  onClick={handleCopyTitle}
                  className="text-emerald-400 hover:text-emerald-300 flex items-center gap-1 font-mono text-[10px]"
                >
                  {copiedTitle ? <Check size={11} /> : <Copy size={11} />}
                  <span>{copiedTitle ? 'Copied!' : 'Copy'}</span>
                </button>
              </div>
              <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-2.5 text-xs text-white font-bold truncate">
                {displayTitle}
              </div>
            </div>

            {/* Generated Description & Hashtags Field */}
            <div className="space-y-1.5">
              <div className="flex items-center justify-between text-[11px] font-bold text-zinc-300">
                <span>Caption &amp; Hashtags</span>
                <button
                  onClick={handleCopyDesc}
                  className="text-emerald-400 hover:text-emerald-300 flex items-center gap-1 font-mono text-[10px]"
                >
                  {copiedDesc ? <Check size={11} /> : <Copy size={11} />}
                  <span>{copiedDesc ? 'Copied!' : 'Copy'}</span>
                </button>
              </div>
              <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-2.5 text-xs text-zinc-300 leading-relaxed font-sans h-24 overflow-y-auto whitespace-pre-wrap scrollbar-thin scrollbar-thumb-zinc-800">
                {autoGeneratedDesc}
              </div>
            </div>
          </div>

          {/* FINAL DOWNLOAD ACTION BUTTON */}
          {isReady && status.outputFile && (
            <a
              href={status.outputFile}
              download={mode === 'audioClean' ? 'itnavideo-clean-studio-audio.mp3' : `itnavideo-${mode || 'reel'}.mp4`}
              className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-emerald-500 to-teal-400 hover:from-emerald-400 hover:to-teal-300 text-slate-950 font-black text-sm transition-all flex items-center justify-center gap-2 shadow-[0_0_24px_rgba(16,185,129,0.4)] hover:scale-102"
            >
              <Download size={18} />
              <span>{mode === 'audioClean' ? 'Download Clean Studio Audio (MP3)' : 'Download Ready HD Video (MP4)'}</span>
            </a>
          )}
        </div>

      </div>
    </div>
  );
}
