export default function AdminVideosPage() {
  return (
    <div className="space-y-8">
      <div className="rounded-lg border border-zinc-800 bg-zinc-900 p-8">
        <h1 className="text-4xl font-black text-white">Videos</h1>
        <p className="mt-3 text-zinc-400">
          Founder view for generation and render operations. This page tracks what should become the production render queue.
        </p>
      </div>

      <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">
        <InfoCard title="Planning" value="Gemini" note="Voice analysis and scene direction." />
        <InfoCard title="Captions" value="English default" note="Translated subtitles are generated by default." />
        <InfoCard title="Visuals" value="Local first" note="Owned assets and creator uploads first." />
        <InfoCard title="Render" value="FFmpeg" note="Final assembly and MP4 export." />
      </div>

      <div className="rounded-lg border border-zinc-800 bg-zinc-900 p-6">
        <h2 className="text-2xl font-black text-white">Next backend upgrade</h2>
        <p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-400">
          Move long-running generation into a Render-backed queue so mobile users can lock their screen and return later without depending on the browser tab.
        </p>
      </div>
    </div>
  );
}

function InfoCard({ title, value, note }) {
  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-900 p-5">
      <p className="text-xs font-bold uppercase tracking-[0.18em] text-zinc-500">{title}</p>
      <p className="mt-2 text-2xl font-black text-white">{value}</p>
      <p className="mt-2 text-sm leading-6 text-zinc-500">{note}</p>
    </div>
  );
}
