export type SeoPageKind = "tool" | "useCase" | "comparison" | "alternative";

export type SeoFaq = {
  question: string;
  answer: string;
};

export type SeoInternalLink = {
  label: string;
  href: string;
};

export type SeoContentPage = {
  kind: SeoPageKind;
  slug: string;
  path: string;
  title: string;
  description: string;
  h1: string;
  eyebrow: string;
  hero: string;
  shortExplanation: string;
  primaryKeyword: string;
  relatedKeywords: string[];
  dashboardType: string;
  previewImage: string;
  howItWorks: string[];
  benefits: string[];
  useCases: string[];
  whyItnavideo: string[];
  faqs: SeoFaq[];
  internalLinks: SeoInternalLink[];
};

const toolLink = (slug: string, label: string): SeoInternalLink => ({ label, href: `/tools/${slug}` });
const audienceLink = (slug: string, label: string): SeoInternalLink => ({ label, href: `/use-cases/${slug}` });
const blogLink = (slug: string, label: string): SeoInternalLink => ({ label, href: `/blog/${slug}` });
const compareLink = (slug: string, label: string): SeoInternalLink => ({ label, href: `/compare/${slug}` });
const alternativeLink = (slug: string, label: string): SeoInternalLink => ({ label, href: `/alternatives/${slug}` });

const allVideoTypes = [
  "Auto Caption Video",
  "Compare Explainer Video",
  "Long Video Promo",
  "Whiteboard Video",
  "Typography Video",
];

const commonWhy = [
  "It uses focused Video Types instead of a confusing manual timeline editor.",
  "It is built for mobile-first 9:16 reels, Shorts, and short social videos.",
  `It can support multiple creator workflows, including ${allVideoTypes.slice(0, 4).join(", ")}, ${allVideoTypes.slice(4).join(", ")}.`,
  "It keeps the workflow conversion-focused: upload, generate, review, and download.",
];

const page = (item: Omit<SeoContentPage, "path"> & { basePath: "/tools" | "/use-cases" | "/compare" | "/alternatives" }): SeoContentPage => ({
  ...item,
  path: `${item.basePath}/${item.slug}`,
});

export const toolSeoPages: SeoContentPage[] = [
  page({
    kind: "tool",
    basePath: "/tools",
    slug: "image-to-video-ai",
    title: "Image to Video AI – 16:9 Widescreen Video Generator | Itnavideo",
    description: "Upload voiceover audio and photos. AI automatically segments scenes, adds Ken Burns pan & zoom, 2.5D parallax subtitles, and BGM ducking.",
    h1: "Image to Video AI for cinematic 16:9 widescreen videos",
    eyebrow: "Image to Video AI",
    hero: "Upload voiceover narration and any number of images. AI synchronizes scenes per line, adds continuous Ken Burns motion, 2.5D parallax subtitles, and cinematic transitions.",
    shortExplanation: "Transform raw audio narration and still images into high-production 16:9 widescreen videos at 30 FPS. Up to 5 minutes of video with automated scene cutting and curated visual fallbacks.",
    primaryKeyword: "image to video ai",
    relatedKeywords: ["image to video generator", "ken burns video maker", "voiceover to video ai", "photo to video maker", "ai video generator"],
    dashboardType: "image-to-video-ai",
    previewImage: "https://storage.googleapis.com/itnavideo-media-assets/ChatGPT_Image_Sep_7_2026_04_53_09_PM_suv9x7.png",
    howItWorks: [
      "Upload your voiceover recording up to 5 minutes long.",
      "Optionally upload any number of images or let AI use curated 16:9 visuals.",
      "Configure camera motion (Ken Burns pan/zoom) and 2.5D parallax subtitle styles.",
      "Render a complete 16:9 widescreen MP4 at 30 frames per second.",
    ],
    benefits: [
      "No image limit — upload 5, 20, or 50 images, or none at all.",
      "Automatic sentence-by-sentence scene detection from Speech AI audio transcript.",
      "Smooth Ken Burns camera movement (1.0x to 1.18x continuous pan & zoom).",
      "Dynamic background music auto-ducking behind speech.",
    ],
    useCases: [
      "YouTube educational & explainer videos",
      "Documentaries and biographical stories",
      "Product walkthroughs and case studies",
      "Audiobook chapters & podcast visualizers",
    ],
    whyItnavideo: commonWhy,
    faqs: [
      {
        question: "How many images can I upload in Image to Video AI?",
        answer: "There is no fixed limit. You can upload as many images as you need. If you do not upload any images, the system automatically selects curated 16:9 visuals from Itnavideo.",
      },
      {
        question: "What is the maximum duration and frame rate?",
        answer: "Image to Video AI supports up to 5 minutes per video rendered at a smooth 30 FPS in 16:9 (1920x1080) widescreen resolution.",
      },
      {
        question: "How are credits calculated for Image to Video AI?",
        answer: "Image to Video AI costs 2 credits per 1 minute of generated video.",
      },
    ],
    internalLinks: [
      toolLink("faceless-video-generator", "Faceless Video Generator"),
      toolLink("ai-audio-cleaner", "AI Audio Cleaner"),
    ],
  }),
  page({
    kind: "tool",
    basePath: "/tools",
    slug: "auto-caption-video-generator",
    title: "Auto Caption Video Generator for Reels and Shorts",
    description: "Use Itnavideo as an auto caption generator and video caption generator for reels, Shorts, podcasts, lessons, and talking videos.",
    h1: "Auto caption video generator for reels, Shorts, and talking videos",
    eyebrow: "Auto Caption Video",
    hero: "Upload a video with speech, choose a caption style, and generate a polished captioned MP4 without manually timing subtitles.",
    shortExplanation: "This page targets creators who need an auto caption generator, video caption generator, and AI subtitle workflow for short-form content. Itnavideo keeps the original video as the main content and adds readable, word-timed captions on top.",
    primaryKeyword: "auto caption video generator",
    relatedKeywords: ["auto caption generator", "video caption generator", "AI subtitle generator", "caption reels", "AI video generator"],
    dashboardType: "auto-caption-video",
    previewImage: "/preview/Auto Caption Reel.png",
    howItWorks: [
      "Upload a short video with clear speech.",
      "Itnavideo transcribes the audio with Speech AI.",
      "Choose a caption style, size, position, text color, and highlight color.",
      "Render a 9:16 MP4 with burned-in captions ready for social platforms.",
    ],
    benefits: [
      "Save manual caption timing work in CapCut or Premiere.",
      "Make videos easier to watch on mute.",
      "Use caption styles that look like real creator reels.",
      "Keep the original video and audio unchanged.",
    ],
    useCases: [
      "Instagram Reels with captions",
      "YouTube Shorts subtitles",
      "Podcast clips",
      "Course clips and educational lessons",
      "Business talking-head clips",
    ],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Can I use this as an auto caption generator?", answer: "Yes. Upload a video with speech, pick a caption style, and render a captioned MP4." },
      { question: "Are captions burned into the final video?", answer: "Yes. Captions are rendered into the MP4 so they show on Instagram, YouTube Shorts, TikTok, and other platforms." },
      { question: "Does Itnavideo support Hinglish captions?", answer: "The current caption flow supports English and Roman Hinglish output from the supported transcription pipeline." },
    ],
    internalLinks: [
      toolLink("ai-reel-generator", "AI reel generator"),
      blogLink("how-to-add-captions-to-instagram-reels", "How to add captions to Instagram Reels"),
      blogLink("how-to-add-captions-to-youtube-shorts", "How to add captions to YouTube Shorts"),
      compareLink("best-auto-caption-tools", "Best auto caption tools"),
    ],
  }),
  page({
    kind: "tool",
    basePath: "/tools",
    slug: "ai-reel-generator",
    title: "AI Reel Generator for Creators, Coaches, and Businesses",
    description: "Create reels with Itnavideo's AI reel generator for captions, creator videos, explainers, promos, and custom AI reels.",
    h1: "AI reel generator for polished short videos without manual editing",
    eyebrow: "AI Reel Generator",
    hero: "Create short-form reels from real videos, voiceovers, images, thumbnails, or prompts using focused Itnavideo Video Types.",
    shortExplanation: "Itnavideo is an AI video generator and AI reel generator for creators who want publish-ready 9:16 videos without opening a traditional timeline editor.",
    primaryKeyword: "AI reel generator",
    relatedKeywords: ["AI video generator", "reel maker", "AI shorts generator", "video generator", "short form video generator"],
    dashboardType: "dynamic-creator-reel",
    previewImage: "/preview/Dynamic Creator Reel.png",
    howItWorks: [
      "Choose the Video Type that matches your goal.",
      "Upload the required video, audio, images, thumbnail, or prompt.",
      "Itnavideo prepares transcription, captions, scene timing, or layout.",
      "Render and download a mobile-first MP4.",
    ],
    benefits: [
      "One platform for captions, creator reels, explainers, promos, and custom reels.",
      "No manual cuts or complex editing timeline.",
      "Built around creator use cases, not generic stock video slides.",
      "Conversion-focused workflow from upload to download.",
    ],
    useCases: [
      "Creator reels",
      "AI Shorts",
      "Educational explainers",
      "Long video promos",
      "Business and coaching videos",
    ],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Is Itnavideo an AI video generator?", answer: "Yes. Itnavideo generates short-form videos from uploaded content and focused Video Type workflows." },
      { question: "Is this a manual editor?", answer: "No. Itnavideo is designed for users who want to upload content and let the system handle the structure and render." },
      { question: "What Video Types are available?", answer: `Itnavideo tracks ${allVideoTypes.join(", ")} as product workflows.` },
    ],
    internalLinks: [
      toolLink("auto-caption-video-generator", "Auto caption video generator"),
      toolLink("custom-ai-reel-generator", "Custom AI reel generator"),
      audienceLink("ai-video-tool-for-creators", "AI video tool for creators"),
      compareLink("best-ai-video-tools-for-reels", "Best AI video tools for reels"),
    ],
  }),
  page({
    kind: "tool",
    basePath: "/tools",
    slug: "custom-ai-reel-generator",
    title: "Custom AI Reel Generator from Prompts and Uploaded Media",
    description: "Describe your reel idea, upload optional images or a logo, and use Itnavideo's Custom AI Reel workflow to create a polished 9:16 video.",
    h1: "Custom AI reel generator for prompt-based short videos",
    eyebrow: "Custom AI Reel",
    hero: "Turn a simple prompt into a structured short video with optional screenshots, images, and logo assets.",
    shortExplanation: "Custom AI Reel is for users who need a flexible AI reel generator when standard Video Types do not fully match the idea.",
    primaryKeyword: "custom AI reel generator",
    relatedKeywords: ["AI reel generator", "AI video generator", "prompt to reel", "custom reel maker"],
    dashboardType: "custom-ai-reel",
    previewImage: "/preview/Custom AI Reel.png",
    howItWorks: [
      "Describe the video in simple English.",
      "Optionally upload images, screenshots, and a logo.",
      "Itnavideo creates a structured timeline for the reel.",
      "Render a 9:16 MP4 for social use.",
    ],
    benefits: [
      "Flexible workflow when a fixed Video Type is not enough.",
      "Supports text-only and media-supported reel ideas.",
      "Keeps uploaded media central instead of using random visuals.",
      "Useful for product promos, announcements, and custom explainers.",
    ],
    useCases: ["Product explainers", "Launch videos", "App promos", "Screenshot reels", "Simple text-based campaigns"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Can I make a reel from only a prompt?", answer: "Yes, text-only Custom AI Reels can be created when the prompt is clear enough." },
      { question: "Can I upload screenshots?", answer: "Yes. Custom AI Reel is designed to use optional uploaded images and screenshots." },
      { question: "Does it add random stock assets?", answer: "The planned workflow prioritizes user-uploaded media and structured timeline generation." },
    ],
    internalLinks: [
      toolLink("ai-reel-generator", "AI reel generator"),
      audienceLink("ai-video-tool-for-businesses", "AI video tool for businesses"),
      blogLink("how-to-create-reels-from-audio", "Create reels from audio"),
    ],
  }),
  page({
    kind: "tool",
    basePath: "/tools",
    slug: "long-video-promo-maker",
    title: "Long Video Promo Maker for YouTube, Podcasts, and Courses",
    description: "Promote long videos with short vertical promos using a thumbnail, title, and promo clip in Itnavideo.",
    h1: "Long video promo maker for short social teasers",
    eyebrow: "Long Video Promo",
    hero: "Use a thumbnail, title, and short clip to create a vertical promo for your long-form content.",
    shortExplanation: "This page targets creators who need a reel maker for YouTube videos, podcasts, courses, webinars, lectures, noha, munajat, bayan, and long-form episodes.",
    primaryKeyword: "long video promo maker",
    relatedKeywords: ["YouTube promo maker", "podcast clip maker", "AI shorts generator", "reel maker"],
    dashboardType: "long-video-promo",
    previewImage: "/preview/Long Video Promo.png",
    howItWorks: [
      "Upload a thumbnail image.",
      "Add the video title.",
      "Upload a short promo clip.",
      "Render a 9:16 promo reel for Shorts, Reels, or TikTok.",
    ],
    benefits: [
      "Promote long-form content without manually designing a teaser.",
      "Keep the thumbnail and title visible.",
      "Create social clips for YouTube, podcasts, and courses.",
      "Save time when every new long video needs a promo.",
    ],
    useCases: ["YouTube video promos", "Podcast teasers", "Course launches", "Lecture clips", "Religious content promos"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Do I upload the full long video?", answer: "For this workflow, upload a short promo clip plus the thumbnail and title." },
      { question: "Can podcasters use this?", answer: "Yes. It works well for podcast episode teasers and interview highlights." },
      { question: "Can I use it for YouTube Shorts?", answer: "Yes. The output is a vertical MP4 suitable for YouTube Shorts and similar platforms." },
    ],
    internalLinks: [
      audienceLink("ai-video-tool-for-podcasters", "AI video tool for podcasters"),
      audienceLink("ai-video-tool-for-course-creators", "AI video tool for course creators"),
      blogLink("how-to-turn-long-videos-into-short-promos", "Turn long videos into short promos"),
    ],
  }),
  page({
    kind: "tool",
    basePath: "/tools",
    slug: "compare-explainer-video-maker",
    title: "Compare Explainer Video Maker for Side-by-Side Reels",
    description: "Create comparison videos from voiceover and two images with Itnavideo's Compare Explainer Video Type.",
    h1: "Compare explainer video maker for products, ideas, and concepts",
    eyebrow: "Compare Explainer Video",
    hero: "Build left-vs-right comparison reels with captions, labels, images, and presenter-style elements.",
    shortExplanation: "Use this comparison reel maker for product comparisons, educational explainers, finance topics, coaching content, and business decisions.",
    primaryKeyword: "compare explainer video maker",
    relatedKeywords: ["comparison video maker", "AI video generator", "explainer video maker", "reel maker"],
    dashboardType: "compare-explainer",
    previewImage: "/preview/Compare Explainer.png",
    howItWorks: [
      "Upload a voiceover or speech video.",
      "Upload left and right comparison images.",
      "Add labels for each side.",
      "Render a side-by-side comparison reel.",
    ],
    benefits: [
      "Turns complex choices into a simple visual comparison.",
      "Great for education, reviews, product pages, and finance explainers.",
      "Captions help viewers follow the voiceover.",
      "Presenter elements make the reel more engaging than a static slide.",
    ],
    useCases: ["Product A vs Product B", "Tool comparisons", "Finance explainers", "Education topics", "Course lessons"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "What do I need to upload?", answer: "Upload speech plus two images: one for the left side and one for the right side." },
      { question: "Can I compare services or ideas?", answer: "Yes. Compare Explainer works for products, tools, services, ideas, and concepts." },
      { question: "Does it include captions?", answer: "Yes. Speech-based comparison videos can use captions from the uploaded voiceover." },
    ],
    internalLinks: [
      toolLink("compare-explainer-video-maker", "Compare explainer video maker"),
      audienceLink("ai-video-tool-for-teachers", "AI video tool for teachers"),
      compareLink("best-ai-video-tools-for-reels", "Best AI video tools for reels"),
    ],
  }),
  page({
    kind: "tool",
    basePath: "/tools",
    slug: "auto-draw-explainer-video-generator",
    title: "Auto Draw Explainer Video Generator for Teaching Reels",
    description: "Create whiteboard and notes-style explainer reels from audio or video speech with Itnavideo's Auto Draw Explainer.",
    h1: "Auto draw explainer video generator for whiteboard-style reels",
    eyebrow: "Auto Draw Explainer Video",
    hero: "Upload speech and create a notes-style explainer where headings, bullets, sketches, and highlights reveal with the lesson.",
    shortExplanation: "This AI video generator helps teachers, coaches, and course creators turn lessons into visual reels without drawing manually.",
    primaryKeyword: "auto draw explainer video generator",
    relatedKeywords: ["whiteboard explainer video", "AI video generator", "teaching reels", "explainer video maker"],
    dashboardType: "auto-draw-explainer",
    previewImage: "/preview/Auto Draw Explainer.png",
    howItWorks: [
      "Upload audio or video with clear speech.",
      "Itnavideo transcribes the message.",
      "Auto Draw plans notes, highlights, sketches, and reveal timing.",
      "Render a clean educational 9:16 explainer.",
    ],
    benefits: [
      "No drawing skill required.",
      "Useful for lessons, concepts, study notes, and course clips.",
      "Makes educational content more visual.",
      "Works well for teachers and coaches.",
    ],
    useCases: ["Whiteboard explainers", "Study notes", "Course clips", "Coaching lessons", "Concept breakdowns"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Do I need to draw anything?", answer: "No. Auto Draw builds visual notes from the uploaded speech." },
      { question: "Is this for teachers?", answer: "Yes. It is designed for educators, course creators, coaches, and study content." },
      { question: "Can I upload only audio?", answer: "Yes. Auto Draw can work from audio or video with speech." },
    ],
    internalLinks: [
      audienceLink("ai-video-tool-for-teachers", "AI video tool for teachers"),
      audienceLink("ai-video-tool-for-course-creators", "AI video tool for course creators"),
      blogLink("how-to-create-reels-from-audio", "Create reels from audio"),
    ],
  }),
  page({
    kind: "tool",
    basePath: "/tools",
    slug: "dynamic-explainer-video-generator",
    title: "Dynamic Explainer Video Generator for Creator Reels",
    description: "Turn talking-head videos into dynamic creator reels with transcript-led typography and short-form pacing.",
    h1: "Dynamic explainer video generator for creator-led reels",
    eyebrow: "Dynamic Creator Reel Video",
    hero: "Upload a talking-head video and create a creator-style reel with key phrases, typography, and polished short-form structure.",
    shortExplanation: "This page targets users searching for an AI video generator, dynamic explainer video generator, and reel maker for creator videos.",
    primaryKeyword: "dynamic explainer video generator",
    relatedKeywords: ["AI video generator", "creator reel maker", "AI reel generator", "video generator"],
    dashboardType: "dynamic-creator-reel",
    previewImage: "/preview/Dynamic Creator Reel.png",
    howItWorks: [
      "Upload a talking-head video with speech.",
      "Itnavideo transcribes the speech.",
      "The workflow highlights key phrases with creator-style typography.",
      "Render a 9:16 reel for social platforms.",
    ],
    benefits: [
      "Make talking videos feel edited without manual typography work.",
      "Keep the creator as the main visual.",
      "Avoid unrelated stock visuals.",
      "Create short-form content from real speech.",
    ],
    useCases: ["Founder clips", "Coach videos", "Education reels", "Business explainers", "Personal brand clips"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Does this use my real video?", answer: "Yes. Dynamic Creator Reel keeps the uploaded creator video as the main visual." },
      { question: "Can I use only audio?", answer: "This workflow is intended for talking-head video because the creator video is the core visual." },
      { question: "What makes it different from Auto Caption?", answer: "Auto Caption focuses on captions only. Dynamic Creator Reel adds key phrase typography and creator-style pacing." },
    ],
    internalLinks: [
      audienceLink("ai-video-tool-for-creators", "AI video tool for creators"),
      audienceLink("ai-video-tool-for-coaches", "AI video tool for coaches"),
      toolLink("auto-caption-video-generator", "Auto caption video generator"),
    ],
  }),
];

export const useCaseSeoPages: SeoContentPage[] = [
  page({
    kind: "useCase",
    basePath: "/use-cases",
    slug: "ai-video-tool-for-creators",
    title: "AI Video Tool for Creators Who Need Reels Fast",
    description: "Itnavideo helps creators turn videos, voiceovers, prompts, thumbnails, and images into polished short-form videos.",
    h1: "AI video tool for creators who need consistent reels",
    eyebrow: "For creators",
    hero: "Create captioned videos, dynamic creator reels, explainers, promos, and custom AI reels without editing every clip by hand.",
    shortExplanation: "Creators need a repeatable AI video generator and reel maker that supports real content, not generic slides. Itnavideo is built around focused Video Types for common creator workflows.",
    primaryKeyword: "AI video tool for creators",
    relatedKeywords: ["AI video generator", "AI reel generator", "reel maker", "video generator"],
    dashboardType: "dynamic-creator-reel",
    previewImage: "/preview/Dynamic Creator Reel.png",
    howItWorks: ["Choose a creator-focused Video Type.", "Upload your video, voiceover, image, thumbnail, or prompt.", "Let Itnavideo prepare captions, timing, layout, or scene structure.", "Render and download your reel."],
    benefits: ["Save editing time.", "Create more consistently.", "Repurpose existing content.", "Use one platform for multiple creator formats."],
    useCases: ["Talking-head reels", "Captioned clips", "Long video promos", "Comparison explainers", "Custom AI reels"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Is Itnavideo for full-time creators?", answer: "Yes. It is useful for creators who need repeatable short-form output without editing every reel manually." },
      { question: "Can I use my own video?", answer: "Yes. Several Video Types are built around user-uploaded videos and voiceovers." },
      { question: "Can I create different styles of reels?", answer: "Yes. Itnavideo has focused Video Types for captions, creator videos, explainers, promos, and custom reels." },
    ],
    internalLinks: [toolLink("ai-reel-generator", "AI reel generator"), toolLink("auto-caption-video-generator", "Auto caption video generator"), blogLink("how-to-create-reels-from-audio", "Create reels from audio")],
  }),
  page({
    kind: "useCase",
    basePath: "/use-cases",
    slug: "ai-video-tool-for-coaches",
    title: "AI Video Tool for Coaches and Consultants",
    description: "Create coaching reels, lesson clips, captioned talking videos, and short explainers with Itnavideo.",
    h1: "AI video tool for coaches who want more short-form content",
    eyebrow: "For coaches",
    hero: "Turn coaching ideas, voiceovers, and talking videos into reels that explain, teach, and convert.",
    shortExplanation: "Coaches need clear short videos for trust, education, and lead generation. Itnavideo helps turn real teaching content into polished reels.",
    primaryKeyword: "AI video tool for coaches",
    relatedKeywords: ["AI reel generator", "coach video maker", "AI video generator", "reel maker"],
    dashboardType: "dynamic-creator-reel",
    previewImage: "/preview/Dynamic Creator Reel.png",
    howItWorks: ["Record a quick talking video or voice note.", "Choose Dynamic Creator Reel, Auto Caption, or Auto Draw.", "Generate captions, typography, or notes-style visuals.", "Download and post."],
    benefits: ["Teach without complex editing.", "Repurpose coaching calls or lessons.", "Create authority-building reels.", "Make content easier to watch on mute."],
    useCases: ["Mindset tips", "Business coaching", "Fitness coaching", "Career advice", "Consulting explainers"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Can coaches use Itnavideo for talking videos?", answer: "Yes. Dynamic Creator Reel and Auto Caption are strong fits for coaching clips." },
      { question: "Can I create educational note-style reels?", answer: "Yes. Auto Draw Explainer can turn speech into visual notes-style content." },
      { question: "Does it help with lead generation content?", answer: "It helps create clearer, more consistent reels that can support authority and conversion." },
    ],
    internalLinks: [toolLink("dynamic-explainer-video-generator", "Dynamic explainer video generator"), toolLink("auto-draw-explainer-video-generator", "Auto Draw explainer"), audienceLink("ai-video-tool-for-course-creators", "AI video tool for course creators")],
  }),
  page({
    kind: "useCase",
    basePath: "/use-cases",
    slug: "ai-video-tool-for-teachers",
    title: "AI Video Tool for Teachers and Educators",
    description: "Create whiteboard explainers, captioned lesson clips, comparison videos, and study reels with Itnavideo.",
    h1: "AI video tool for teachers making educational reels",
    eyebrow: "For teachers",
    hero: "Turn lessons, voiceovers, and topic explanations into short videos students can watch on mobile.",
    shortExplanation: "Teachers and educators can use Itnavideo as an AI video generator for whiteboard explainers, comparison lessons, captions, and short study content.",
    primaryKeyword: "AI video tool for teachers",
    relatedKeywords: ["whiteboard video maker", "AI video generator", "education reel maker", "explainer video maker"],
    dashboardType: "auto-draw-explainer",
    previewImage: "/preview/Auto Draw Explainer.png",
    howItWorks: ["Upload a lesson voiceover or short teaching video.", "Choose Auto Draw, Compare Explainer, or Auto Caption.", "Generate notes, comparison visuals, or captions.", "Download a 9:16 educational reel."],
    benefits: ["Turn lessons into visual content.", "Support mobile learning.", "Make complex topics easier to understand.", "Create repeatable study content."],
    useCases: ["Whiteboard lessons", "Exam tips", "Concept comparisons", "Study notes", "Course previews"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Can teachers create whiteboard videos?", answer: "Yes. Auto Draw Explainer is designed for notes and whiteboard-style educational reels." },
      { question: "Can I compare two concepts?", answer: "Yes. Compare Explainer works well for two-topic educational comparisons." },
      { question: "Is the output mobile-friendly?", answer: "Yes. Current outputs are focused on 9:16 vertical short videos." },
    ],
    internalLinks: [toolLink("auto-draw-explainer-video-generator", "Auto Draw explainer"), toolLink("compare-explainer-video-maker", "Compare explainer"), blogLink("how-to-create-reels-from-audio", "Create reels from audio")],
  }),
  page({
    kind: "useCase",
    basePath: "/use-cases",
    slug: "ai-video-tool-for-businesses",
    title: "AI Video Tool for Small Businesses and Brands",
    description: "Use Itnavideo to create business reels, product explainers, comparison videos, promos, captions, and custom AI reels.",
    h1: "AI video tool for businesses that need more social content",
    eyebrow: "For businesses",
    hero: "Create product explainers, service comparisons, promo videos, and branded short-form content faster.",
    shortExplanation: "Small businesses need social video but often lack editing time. Itnavideo gives teams focused Video Types for product education and content marketing.",
    primaryKeyword: "AI video tool for businesses",
    relatedKeywords: ["AI video generator", "business reel maker", "video generator", "AI shorts generator"],
    dashboardType: "custom-ai-reel",
    previewImage: "/preview/Custom AI Reel.png",
    howItWorks: ["Choose a business use case.", "Upload clips, images, screenshots, voiceover, thumbnail, or prompt.", "Generate a focused business reel.", "Download and publish."],
    benefits: ["Create more product content.", "Explain services visually.", "Make comparison videos for buyer education.", "Repurpose existing assets."],
    useCases: ["Product explainers", "Service promos", "Feature comparisons", "Founder clips", "Offer announcements"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Can businesses use Itnavideo for product videos?", answer: "Yes. Custom AI Reel, Compare Explainer, and Long Video Promo can support product and service content." },
      { question: "Can I use screenshots?", answer: "Custom AI Reel supports optional uploaded images and screenshots in its milestone workflow." },
      { question: "Is this faster than editing manually?", answer: "The goal is to reduce manual editing by turning uploads and prompts into structured short videos." },
    ],
    internalLinks: [toolLink("custom-ai-reel-generator", "Custom AI reel generator"), toolLink("compare-explainer-video-maker", "Compare explainer"), audienceLink("ai-video-tool-for-creators", "AI video tool for creators")],
  }),
  page({
    kind: "useCase",
    basePath: "/use-cases",
    slug: "ai-video-tool-for-podcasters",
    title: "AI Video Tool for Podcasters and Interview Clips",
    description: "Create captioned podcast clips, episode teasers, and long video promos for social platforms with Itnavideo.",
    h1: "AI video tool for podcasters creating social clips",
    eyebrow: "For podcasters",
    hero: "Turn podcast clips into captioned reels and vertical promos that help people discover the full episode.",
    shortExplanation: "Podcasters need short clips that work on mute and lead viewers back to the full episode. Itnavideo supports captioning, promo layouts, and creator-style reels.",
    primaryKeyword: "AI video tool for podcasters",
    relatedKeywords: ["podcast clip maker", "auto caption generator", "AI reel generator", "YouTube Shorts generator"],
    dashboardType: "long-video-promo",
    previewImage: "/preview/Long Video Promo.png",
    howItWorks: ["Upload a podcast clip or promo segment.", "Use Auto Caption or Long Video Promo.", "Add captions, thumbnail, or title where needed.", "Download a social-ready clip."],
    benefits: ["Make clips watchable on mute.", "Promote full episodes.", "Create repeatable short-form content.", "Use thumbnails and titles for better context."],
    useCases: ["Podcast teasers", "Interview highlights", "Guest quote clips", "Episode promos", "Educational podcast clips"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Can I caption podcast clips?", answer: "Yes. Auto Caption Video is useful for podcast clips with speech." },
      { question: "Can I promote a full episode?", answer: "Yes. Long Video Promo is designed for thumbnail and title-based promos." },
      { question: "Does it export MP4?", answer: "Yes. Itnavideo renders downloadable MP4 output." },
    ],
    internalLinks: [toolLink("long-video-promo-maker", "Long video promo maker"), toolLink("auto-caption-video-generator", "Auto caption video generator"), blogLink("how-to-turn-long-videos-into-short-promos", "Long video promo guide")],
  }),
  page({
    kind: "useCase",
    basePath: "/use-cases",
    slug: "ai-video-tool-for-course-creators",
    title: "AI Video Tool for Course Creators and Online Educators",
    description: "Repurpose course lessons into captioned reels, whiteboard explainers, comparison videos, and promo clips with Itnavideo.",
    h1: "AI video tool for course creators turning lessons into reels",
    eyebrow: "For course creators",
    hero: "Create lesson clips, course promos, and educational reels from existing teaching content.",
    shortExplanation: "Course creators can use Itnavideo to create short videos that promote lessons, explain concepts, and make educational content more discoverable.",
    primaryKeyword: "AI video tool for course creators",
    relatedKeywords: ["course video maker", "AI video generator", "whiteboard video maker", "reel maker"],
    dashboardType: "auto-draw-explainer",
    previewImage: "/preview/Auto Draw Explainer.png",
    howItWorks: ["Select a course lesson or voiceover.", "Choose Auto Draw, Auto Caption, Compare, or Long Video Promo.", "Generate a short visual version.", "Share it on social or landing pages."],
    benefits: ["Repurpose course content.", "Create lead magnets.", "Explain concepts visually.", "Promote modules and webinars."],
    useCases: ["Lesson previews", "Module promos", "Whiteboard summaries", "Course comparison clips", "Student-friendly recaps"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Can I use existing lessons?", answer: "Yes. Upload clear clips or voiceovers and choose the Video Type that matches the goal." },
      { question: "Which Video Type is best for teaching?", answer: "Auto Draw Explainer is strong for teaching concepts, while Auto Caption helps with lesson clips." },
      { question: "Can I promote a webinar?", answer: "Yes. Long Video Promo can create a short teaser using a thumbnail, title, and promo clip." },
    ],
    internalLinks: [toolLink("auto-draw-explainer-video-generator", "Auto Draw explainer"), toolLink("long-video-promo-maker", "Long video promo maker"), blogLink("how-to-create-reels-from-audio", "Create reels from audio")],
  }),
];

export const comparisonSeoPages: SeoContentPage[] = [
  page({
    kind: "comparison",
    basePath: "/compare",
    slug: "best-ai-video-tools-for-reels",
    title: "Best AI Video Tools for Reels: What Creators Should Compare",
    description: "Compare AI video tools for reels, captions, Shorts, explainers, promos, and creator workflows, and see where Itnavideo fits.",
    h1: "Best AI video tools for reels: what matters before you choose",
    eyebrow: "AI video tool comparison",
    hero: "The best AI video tool is not just the one with the most effects. It should help you create watchable, clear, mobile-first reels from real content.",
    shortExplanation: "This comparison page targets AI video generator, AI reel generator, AI shorts generator, and reel maker searches while helping creators choose based on real workflow needs.",
    primaryKeyword: "best AI video tools for reels",
    relatedKeywords: ["AI video generator", "AI reel generator", "AI shorts generator", "reel maker"],
    dashboardType: "dynamic-creator-reel",
    previewImage: "/preview/Dynamic Creator Reel.png",
    howItWorks: ["Start with your content type.", "Check if the tool handles captions and timing.", "Compare how much manual editing is still required.", "Choose the workflow that gets you to a ready MP4 fastest."],
    benefits: ["Avoid choosing based only on flashy demos.", "Match the tool to your actual content workflow.", "Prioritize captions, mobile output, and repeatable formats.", "Understand where Itnavideo fits against broad editors."],
    useCases: ["Creator reels", "Captioned videos", "Education content", "Promo clips", "Business videos"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "What should I look for in an AI video tool?", answer: "Look for accurate captions, mobile-first output, useful Video Types, export quality, and a workflow that saves real editing time." },
      { question: "Is Itnavideo a broad video editor?", answer: "No. Itnavideo focuses on upload-to-render Video Types instead of manual timeline editing." },
      { question: "Can one tool handle every video format?", answer: "Usually not well. It is better to choose a tool that fits your repeated content workflow." },
    ],
    internalLinks: [toolLink("ai-reel-generator", "AI reel generator"), toolLink("auto-caption-video-generator", "Auto caption generator"), compareLink("best-auto-caption-tools", "Best auto caption tools")],
  }),
  page({
    kind: "comparison",
    basePath: "/compare",
    slug: "best-auto-caption-tools",
    title: "Best Auto Caption Tools for Reels and Shorts",
    description: "Compare auto caption tools for reels, Shorts, podcasts, lessons, and creator videos, including what to look for before choosing one.",
    h1: "Best auto caption tools for short-form creators",
    eyebrow: "Auto caption comparison",
    hero: "Auto captions are not only about transcription. The best tools also handle style, safe-area placement, readability, and final MP4 export.",
    shortExplanation: "This comparison page targets auto caption generator, video caption generator, AI subtitle generator, and auto caption tools searches.",
    primaryKeyword: "best auto caption tools",
    relatedKeywords: ["auto caption generator", "video caption generator", "AI subtitle generator", "caption reels"],
    dashboardType: "auto-caption-video",
    previewImage: "/preview/Auto Caption Reel.png",
    howItWorks: ["Upload a short speaking video.", "Transcription creates word timings.", "The tool groups captions into readable chunks.", "Styles and safe-area placement make the final video social-ready."],
    benefits: ["Save manual caption timing.", "Improve mute viewing.", "Create more accessible videos.", "Make captions look intentional rather than pasted on."],
    useCases: ["Talking reels", "Podcast clips", "YouTube Shorts", "Course clips", "Business videos"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "What makes an auto caption tool good?", answer: "Good auto caption tools need accurate transcription, readable chunking, caption styles, safe placement, and reliable export." },
      { question: "Does Itnavideo focus on captions?", answer: "Yes. Auto Caption Video is a dedicated Video Type for captioning existing videos." },
      { question: "Can captions help SEO?", answer: "Captions can improve engagement and watchability. Search visibility still depends on page content, titles, metadata, and distribution." },
    ],
    internalLinks: [toolLink("auto-caption-video-generator", "Auto caption video generator"), blogLink("how-to-add-captions-to-instagram-reels", "Instagram Reels captions"), blogLink("how-to-add-captions-to-youtube-shorts", "YouTube Shorts captions")],
  }),
  page({
    kind: "comparison",
    basePath: "/compare",
    slug: "itnavideo-vs-invideo",
    title: "Itnavideo vs InVideo AI: Which AI Video Generator is Better for Reels?",
    description: "Compare Itnavideo and InVideo AI. Discover why creators choose Itnavideo's dedicated 1080p Video Types over generic text prompt generators.",
    h1: "Itnavideo vs InVideo AI – Comparison for Short-Form Creators",
    eyebrow: "Competitor Comparison",
    hero: "InVideo AI relies heavily on generic text prompts and stock footage. Itnavideo provides 10 purpose-built Video Types with instant 1080p cloud rendering, Groq Whisper speech transcription, and precise Ken Burns motion.",
    shortExplanation: "If you want fast, zero-watermark 1080p reels, Shorts, and explainers without navigating heavy prompt editors, Itnavideo is built for higher speed and precision.",
    primaryKeyword: "itnavideo vs invideo",
    relatedKeywords: ["invideo alternative", "invideo vs itnavideo", "best invideo alternative", "ai video generator"],
    dashboardType: "image-to-video-ai",
    previewImage: "/preview/Auto Caption Reel.png",
    howItWorks: [
      "Upload your voiceover or audio file.",
      "Select your preferred visual style (Realistic, 2D, or 3D).",
      "AI automatically structures scenes and syncs kinetic subtitles.",
      "Render crisp 1080p Full HD MP4 in under 15 seconds.",
    ],
    benefits: [
      "100% 1080p Full HD export on all plans.",
      "Dedicated Video Types (Image to Video AI, Compare, Auto Caption, Audio Cleaner).",
      "No complex timeline keyframing or prompt bloat.",
      "Ultra-fast Groq Whisper speech-to-text accuracy.",
    ],
    useCases: ["Shorts & Reels creators", "Educational explainers", "Product walkthroughs", "Podcast clips"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Why choose Itnavideo over InVideo AI?", answer: "Itnavideo uses dedicated Video Types for specific workflows instead of broad, unpredictable prompt generators, resulting in faster rendering and higher visual consistency." },
      { question: "Is 1080p rendering supported on free credits?", answer: "Yes! All Itnavideo exports are rendered in full 1080p HD." },
    ],
    internalLinks: [toolLink("image-to-video-ai", "Image to Video AI"), compareLink("best-ai-video-tools-for-reels", "Best AI video tools for reels")],
  }),
  page({
    kind: "comparison",
    basePath: "/compare",
    slug: "itnavideo-vs-capcut",
    title: "Itnavideo vs CapCut: Automated Cloud Render vs Manual Timeline Editing",
    description: "Compare Itnavideo and CapCut. Learn why creators switch to Itnavideo for automated cloud rendering and instant speech-to-caption workflows.",
    h1: "Itnavideo vs CapCut – Cloud Render vs Manual Timeline",
    eyebrow: "Competitor Comparison",
    hero: "CapCut requires manual timeline drag-and-drop on your local machine. Itnavideo runs entirely on AWS Lambda cloud rendering, generating 1080p HD videos automatically from voiceovers and scripts.",
    shortExplanation: "For creators who want automated short-form video generation without spending hours dragging clips on a local timeline.",
    primaryKeyword: "itnavideo vs capcut",
    relatedKeywords: ["capcut alternative for reels", "capcut vs itnavideo", "automated caption generator", "capcut desktop alternative"],
    dashboardType: "auto-caption-reel",
    previewImage: "/preview/Auto Caption Reel.png",
    howItWorks: [
      "Drop your raw audio or video recording.",
      "Groq Whisper transcribes speech in milliseconds.",
      "AI applies kinetic subtitles, background music ducking, and Ken Burns camera motion.",
      "Export 1080p MP4 directly to your device.",
    ],
    benefits: [
      "Zero local CPU/RAM load — rendering happens on AWS Lambda cloud.",
      "Automatic word-level timestamp grouping for kinetic captions.",
      "No manual timeline keyframing needed.",
      "Clean 1080p exports without heavy desktop app installation.",
    ],
    useCases: ["Talking-head reels", "Course clips", "Faceless video shorts", "Audiobook visualizers"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Do I need a high-end PC like CapCut requires?", answer: "No! Itnavideo processes everything in the cloud, so it works smoothly on any device or laptop." },
      { question: "Can I generate auto captions like CapCut?", answer: "Yes! Itnavideo's Auto Caption Reel uses Groq Whisper for instant, ultra-accurate word highlighting." },
    ],
    internalLinks: [toolLink("auto-caption-generator", "Auto caption generator"), toolLink("ai-audio-cleaner", "AI audio cleaner")],
  }),
  page({
    kind: "comparison",
    basePath: "/compare",
    slug: "invideo-free-alternative",
    title: "Best InVideo Free Alternative for Fast 1080p AI Video Creation",
    description: "Looking for an InVideo free alternative? Itnavideo offers zero-watermark 1080p AI video generation, automated captions, and cloud rendering.",
    h1: "The Best InVideo Free Alternative with Zero Timeline Headache",
    eyebrow: "Free SaaS Alternative",
    hero: "Tired of InVideo's heavy watermarks, slow generation queues, and complex credit rules? Itnavideo provides a clean, fast alternative for 1080p short-form videos.",
    shortExplanation: "Get 10 free credits upon signup and create 1080p HD reels, Shorts, and explainers with zero learning curve.",
    primaryKeyword: "invideo free alternative",
    relatedKeywords: ["invideo alternative", "free invideo alternative", "ai video generator no watermark", "best invideo alternative"],
    dashboardType: "image-to-video-ai",
    previewImage: "/preview/Auto Caption Reel.png",
    howItWorks: [
      "Sign up for free and get 10 instant creation credits.",
      "Select a Video Type: Image to Video AI, Auto Caption, or Compare Explainer.",
      "Upload audio or type a script beat.",
      "Download clean 1080p MP4.",
    ],
    benefits: [
      "No low-resolution 720p downgrades.",
      "Instant 0s generation wait time with pre-curated asset libraries.",
      "Clean dark-mode interface with zero ad spam.",
      "Dedicated audio cleaner tool included.",
    ],
    useCases: ["YouTube Shorts", "Instagram Reels", "TikTok Explainers", "Business Demos"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Is Itnavideo really free to try?", answer: "Yes! Every new user gets 10 free credits to test and download 1080p Full HD videos." },
      { question: "Are videos watermarked?", answer: "No! Rendered videos do not have intrusive watermarks." },
    ],
    internalLinks: [toolLink("image-to-video-ai", "Image to Video AI"), compareLink("itnavideo-vs-invideo", "Itnavideo vs InVideo")],
  }),
  page({
    kind: "comparison",
    basePath: "/compare",
    slug: "clipchamp-alternative-for-explainer-videos",
    title: "Clipchamp Alternative for Explainer Videos & Automated Reels",
    description: "Upgrade from Clipchamp to Itnavideo. Create automated 1080p explainer videos, whiteboard notes, and kinetic captions in seconds.",
    h1: "Clipchamp Alternative for Automated 1080p Explainers & Captions",
    eyebrow: "Free SaaS Alternative",
    hero: "Clipchamp requires manual web-editor trimming and offers limited AI automation. Itnavideo turns voiceovers into complete 1080p explainer reels automatically.",
    shortExplanation: "Built for creators, educators, and marketers who want automated video production without spending hours in a browser video editor.",
    primaryKeyword: "clipchamp alternative for explainer videos",
    relatedKeywords: ["clipchamp alternative", "explainer video generator", "auto caption generator", "clipchamp vs itnavideo"],
    dashboardType: "whiteboard-video",
    previewImage: "/preview/Auto Draw Explainer.png",
    howItWorks: [
      "Upload your lesson audio or talking clip.",
      "Choose Whiteboard Explainer or Compare Explainer mode.",
      "AI automatically structures visual beats and captions.",
      "Export 1080p Full HD MP4.",
    ],
    benefits: [
      "Automated scene pacing based on speech recognition.",
      "Built-in stickman & whiteboard sketch animations.",
      "Ultra-fast cloud rendering.",
      "Mobile-optimized 9:16 vertical exports.",
    ],
    useCases: ["Course creators", "Teachers & Educators", "SaaS product walk-throughs", "YouTube Shorts"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "How does Itnavideo compare to Clipchamp?", answer: "Clipchamp is a manual web video editor. Itnavideo is an AI-powered automated video studio that generates complete videos from speech." },
    ],
    internalLinks: [toolLink("whiteboard-video", "Whiteboard Video Maker"), compareLink("best-ai-video-tools-for-reels", "Best AI video tools")],
  }),
];

export const alternativeSeoPages: SeoContentPage[] = [
  page({
    kind: "alternative",
    basePath: "/alternatives",
    slug: "invideo-alternative",
    title: "Best InVideo Alternative for Fast 1080p AI Video Creation | Itnavideo",
    description: "Looking for the best InVideo alternative? Itnavideo offers zero-watermark 1080p AI video generation, Groq speech transcription, and fast cloud rendering.",
    h1: "The Best InVideo Alternative for Fast 1080p AI Reels & Shorts",
    eyebrow: "SaaS Alternative",
    hero: "Switch from InVideo to Itnavideo for faster 1080p cloud renders, zero-watermark video exports, and dedicated Video Types without navigating heavy text prompt builders.",
    shortExplanation: "Itnavideo delivers instant speech-driven 1080p video creation with zero local lag and 0s generation queues.",
    primaryKeyword: "invideo alternative",
    relatedKeywords: ["invideo alternative free", "best invideo alternative", "ai video generator no watermark", "invideo vs itnavideo"],
    dashboardType: "image-to-video-ai",
    previewImage: "/preview/Auto Caption Reel.png",
    howItWorks: [
      "Upload your speech audio or script.",
      "Select your visual style (Realistic, 2D, or 3D).",
      "AI detects scene beats and kinetic subtitle highlights.",
      "Render crisp 1080p Full HD MP4 in under 15 seconds.",
    ],
    benefits: [
      "No heavy watermarks or forced low-res exports.",
      "Ultra-fast Groq Whisper speech transcription.",
      "Dedicated Video Types for specific workflows.",
      "AWS Lambda cloud rendering with zero device lag.",
    ],
    useCases: ["Shorts & Reels creators", "Product explainers", "Marketing videos", "Educational clips"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Why is Itnavideo better than InVideo for short videos?", answer: "Itnavideo uses dedicated Video Types with local preset visual banks, rendering 1080p MP4s in seconds without waiting for unpredictable prompt queues." },
      { question: "Is 1080p export included for free?", answer: "Yes! All renders on Itnavideo are exported in crisp 1080p Full HD." },
    ],
    internalLinks: [toolLink("image-to-video-ai", "Image to Video AI"), compareLink("itnavideo-vs-invideo", "Itnavideo vs InVideo")],
  }),
  page({
    kind: "alternative",
    basePath: "/alternatives",
    slug: "capcut-pc-alternative-for-captions",
    title: "CapCut PC Alternative for Automated Captions & Cloud Render | Itnavideo",
    description: "Upgrade to Itnavideo as your CapCut PC alternative. Automatically generate 1080p kinetic captions and short reels in the cloud.",
    h1: "CapCut PC Alternative for Automated 1080p Captions & Cloud Render",
    eyebrow: "SaaS Alternative",
    hero: "Avoid CapCut's desktop app size, high RAM usage, and manual keyframing. Itnavideo runs 100% in the cloud, generating automated captions and Ken Burns camera motion from your audio.",
    shortExplanation: "Designed for creators who want automated short-form captioning and visual explainers without installing desktop software or dragging clips manually.",
    primaryKeyword: "capcut pc alternative for captions",
    relatedKeywords: ["capcut pc alternative", "capcut desktop alternative", "auto caption generator", "capcut alternative for reels"],
    dashboardType: "auto-caption-reel",
    previewImage: "/preview/Auto Caption Reel.png",
    howItWorks: [
      "Drop raw audio or video into the studio.",
      "Groq Whisper generates millisecond-accurate word timestamps.",
      "Pick your kinetic subtitle preset and audio ducking.",
      "Export 1080p MP4 directly to your device.",
    ],
    benefits: [
      "Zero local RAM/CPU load — process everything on cloud GPUs/CPUs.",
      "Automated word-grouped kinetic subtitle animations.",
      "No manual keyframing or timeline setup.",
      "Clean 1080p exports.",
    ],
    useCases: ["Talking-head reels", "Podcast clips", "Course teasers", "Faceless shorts"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "Can I use Itnavideo on low-RAM laptops?", answer: "Yes! Because rendering happens on AWS Lambda, Itnavideo works fast on any laptop or phone." },
    ],
    internalLinks: [toolLink("auto-caption-generator", "Auto caption generator"), compareLink("itnavideo-vs-capcut", "Itnavideo vs CapCut")],
  }),
  page({
    kind: "alternative",
    basePath: "/alternatives",
    slug: "descript-alternative-for-creators",
    title: "Descript Alternative for Creators: Instant AI Video Studio | Itnavideo",
    description: "Looking for a fast Descript alternative? Itnavideo offers instant speech-driven reels, 1080p cloud renders, and automatic audio cleaning.",
    h1: "Descript Alternative for Short-Form Creators & Video Marketers",
    eyebrow: "SaaS Alternative",
    hero: "Descript is built for long text transcript editing. Itnavideo focuses on short-form conversion reels, kinetic subtitles, whiteboard explainers, and instant 1080p exports.",
    shortExplanation: "Create social-ready reels and Shorts from voiceovers in seconds without managing heavy multi-track timeline sessions.",
    primaryKeyword: "descript alternative for creators",
    relatedKeywords: ["descript alternative", "descript vs itnavideo", "ai audio cleaner", "auto caption generator"],
    dashboardType: "ai-audio-cleaner",
    previewImage: "/preview/Auto Caption Reel.png",
    howItWorks: [
      "Upload speech recording or video clip.",
      "AI transcribes, cleans background noise, and detects speech retakes.",
      "Select kinetic typography or visual explainer format.",
      "Download master 1080p MP4.",
    ],
    benefits: [
      "Includes AI Audio Cleaner for retake removal and studio mastering.",
      "Fast 1080p cloud rendering.",
      "Mobile-first 9:16 vertical presets.",
      "Simple upload-to-render workflow.",
    ],
    useCases: ["Coaches & Founders", "Podcasters", "Educators", "Short-form creators"],
    whyItnavideo: commonWhy,
    faqs: [
      { question: "How is Itnavideo different from Descript?", answer: "Descript is a document-based long video editor. Itnavideo is a short-form video generation engine designed for fast 9:16 reels, captions, and explainers." },
    ],
    internalLinks: [toolLink("ai-audio-cleaner", "AI Audio Cleaner"), toolLink("auto-caption-generator", "Auto Caption Generator")],
  }),
];

export const seoContentPages = [...toolSeoPages, ...useCaseSeoPages, ...comparisonSeoPages, ...alternativeSeoPages];

export function getSeoContentPage(kind: SeoPageKind, slug: string) {
  return seoContentPages.find((page) => page.kind === kind && page.slug === slug);
}

export function getSeoPagesByKind(kind: SeoPageKind) {
  return seoContentPages.filter((page) => page.kind === kind);
}
