// Automatically generated by scripts/upload-whiteboard-icons.mjs
export type WhiteboardIconName = 
  | 'lightbulb' | 'brain' | 'money' | 'clock' | 'book' 
  | 'rocket' | 'heart' | 'trophy' | 'target' | 'shield' 
  | 'chart' | 'star' | 'checkmark' | 'question' | 'fire';

export const WHITEBOARD_ICONS: Record<WhiteboardIconName, string> = {
  "lightbulb": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_lightbulb.svg",
  "brain": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_brain.svg",
  "money": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_money.svg",
  "clock": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_clock.svg",
  "book": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_book.svg",
  "rocket": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_rocket.svg",
  "heart": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_heart.svg",
  "trophy": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_trophy.svg",
  "target": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_target.svg",
  "shield": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_shield.svg",
  "chart": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_chart.svg",
  "star": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_star.svg",
  "checkmark": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_checkmark.svg",
  "question": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_question.svg",
  "fire": "https://storage.googleapis.com/itnavideo-media-assets/Assets/icons/whiteboard_fire.svg"
};

export function resolveWhiteboardIcon(keyword?: string): string {
  if (!keyword) return WHITEBOARD_ICONS['lightbulb'];
  const clean = keyword.toLowerCase().trim();

  if (clean.includes('brain') || clean.includes('mind') || clean.includes('soch') || clean.includes('psycho') || clean.includes('dimagh')) return WHITEBOARD_ICONS['brain'];
  if (clean.includes('money') || clean.includes('paisa') || clean.includes('dolat') || clean.includes('wealth') || clean.includes('finance') || clean.includes('kamao')) return WHITEBOARD_ICONS['money'];
  if (clean.includes('time') || clean.includes('waqt') || clean.includes('ghanta') || clean.includes('clock') || clean.includes('routine') || clean.includes('subah')) return WHITEBOARD_ICONS['clock'];
  if (clean.includes('book') || clean.includes('ilm') || clean.includes('kitab') || clean.includes('quran') || clean.includes('read') || clean.includes('study') || clean.includes('parho')) return WHITEBOARD_ICONS['book'];
  if (clean.includes('rocket') || clean.includes('growth') || clean.includes('fast') || clean.includes('future') || clean.includes('taraqqi') || clean.includes('speed')) return WHITEBOARD_ICONS['rocket'];
  if (clean.includes('heart') || clean.includes('health') || clean.includes('dil') || clean.includes('fitness') || clean.includes('sehat') || clean.includes('mohabbat')) return WHITEBOARD_ICONS['heart'];
  if (clean.includes('trophy') || clean.includes('win') || clean.includes('success') || clean.includes('kaamyabi') || clean.includes('prize') || clean.includes('first')) return WHITEBOARD_ICONS['trophy'];
  if (clean.includes('target') || clean.includes('goal') || clean.includes('maqsad') || clean.includes('focus') || clean.includes('irada')) return WHITEBOARD_ICONS['target'];
  if (clean.includes('shield') || clean.includes('security') || clean.includes('hifazat') || clean.includes('safe') || clean.includes('bachao')) return WHITEBOARD_ICONS['shield'];
  if (clean.includes('chart') || clean.includes('business') || clean.includes('stats') || clean.includes('data') || clean.includes('karobar')) return WHITEBOARD_ICONS['chart'];
  if (clean.includes('star') || clean.includes('rating') || clean.includes('khas') || clean.includes('special') || clean.includes('sitara')) return WHITEBOARD_ICONS['star'];
  if (clean.includes('check') || clean.includes('sahi') || clean.includes('correct') || clean.includes('done') || clean.includes('right')) return WHITEBOARD_ICONS['checkmark'];
  if (clean.includes('quiz') || clean.includes('question') || clean.includes('sawal') || clean.includes('mystery') || clean.includes('pucho')) return WHITEBOARD_ICONS['question'];
  if (clean.includes('fire') || clean.includes('trend') || clean.includes('viral') || clean.includes('aag') || clean.includes('energy') || clean.includes('jazba')) return WHITEBOARD_ICONS['fire'];

  return WHITEBOARD_ICONS['lightbulb'];
}
