import type { PricingPlan } from "@/components/billing/PricingCheckoutCards";

export const pricingPlans: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    price: "$9",
    amountPaise: 75000,
    monthlyVideoLimit: 25,
    description: "Explore all 23 templates. Perfect for getting started.",
    features: ["25 reel credits", "All 23 templates", "HD 1080×1920 export", "No watermark"],
    button: "Get Starter",
    href: "/billing",
    popular: false,
  },
  {
    id: "creator",
    name: "Creator",
    price: "$19",
    amountPaise: 159000,
    monthlyVideoLimit: 60,
    description: "For creators publishing reels regularly.",
    features: ["60 reel credits", "All templates", "Priority render", "Caption styles"],
    button: "Get Creator",
    href: "/billing",
    popular: true,
  },
  {
    id: "business",
    name: "Business",
    price: "$39",
    amountPaise: 325000,
    monthlyVideoLimit: 150,
    description: "For agencies and teams creating at scale.",
    features: ["150 reel credits", "Priority queue", "Commercial usage", "All premium templates"],
    button: "Get Business",
    href: "/billing",
    popular: false,
  },
];
