import type { PricingPlan } from "@/components/billing/PricingCheckoutCards";

export const pricingPlans: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    price: "$19",
    amountPaise: 1900,
    monthlyVideoLimit: 20,
    description: "Perfect for getting started with AI reels.",
    features: ["20 reel credits", "All basic templates", "HD export", "No watermark"],
    button: "Get Starter",
    href: "/billing",
    popular: false,
  },
  {
    id: "creator",
    name: "Creator",
    price: "$39",
    amountPaise: 3900,
    monthlyVideoLimit: 60,
    description: "For creators publishing content regularly.",
    features: ["60 reel credits", "All templates", "Priority render", "Brand kit"],
    button: "Get Creator",
    href: "/billing",
    popular: true,
  },
  {
    id: "business",
    name: "Business",
    price: "$99",
    amountPaise: 9900,
    monthlyVideoLimit: 180,
    description: "For agencies and teams creating at scale.",
    features: ["180 reel credits", "Priority queue", "Commercial usage", "Agency use"],
    button: "Get Business",
    href: "/billing",
    popular: false,
  },
];
