import type { PricingPlan } from "@/components/billing/PricingCheckoutCards";

export const pricingPlans: PricingPlan[] = [
  {
    id: "test",
    name: "Test Itnavideo",
    price: "₹9",
    amountPaise: 900,
    monthlyVideoLimit: 1,
    billingLabel: "one-time",
    validDays: 365,
    description: "For serious first-time users who want to test one real export without a subscription.",
    features: ["1 video", "Max 1 minute video", "1080p export", "No subscription"],
    button: "Pay ₹9",
    href: "/billing",
    popular: false,
  },
  {
    id: "creator",
    name: "Creator",
    price: "₹1,599",
    amountPaise: 159900,
    monthlyVideoLimit: 35,
    description: "For creators publishing almost daily.",
    features: ["35 videos per month", "Max 1 minute exports", "720p exports now", "1080p when unlocked", "Priority render queue"],
    button: "Pay with Razorpay",
    href: "/billing",
    popular: true,
  },
  {
    id: "lite",
    name: "Lite",
    price: "₹799",
    amountPaise: 79900,
    monthlyVideoLimit: 12,
    description: "For creators posting a few times every week.",
    features: ["12 videos per month", "Max 1 minute exports", "720p exports", "Video Explainer reels", "No watermark"],
    button: "Pay with Razorpay",
    href: "/billing",
    popular: false,
  },
  {
    id: "studio",
    name: "Studio",
    price: "₹3,999",
    amountPaise: 399900,
    monthlyVideoLimit: 100,
    description: "For agencies, brands, and teams.",
    features: ["100 videos per month", "Max 1 minute exports", "Priority rendering", "Team-ready workflows", "Custom support"],
    button: "Pay with Razorpay",
    href: "/billing",
    popular: false,
  },
];
