import type { TypographyStyleId, AdvancedStyleBlueprint } from './types';

import bpDynamicPunch from './blueprints/dynamic-punch.json';
import bpDepth3DText from './blueprints/depth-3d-text.json';
import bpDubaiGold from './blueprints/dubai-gold.json';
import bpNeonKinetic from './blueprints/neon-kinetic.json';
import bpPrismPro from './blueprints/prism-pro.json';
import bpPaperII from './blueprints/paper-ii.json';
import bpElevateScript from './blueprints/elevate-script.json';
import bpPlatinumPenthouse from './blueprints/platinum-penthouse.json';
import bpRoyalEmerald from './blueprints/royal-emerald.json';
import bpSilverChrome from './blueprints/silver-chrome.json';
import bpVelvetCrimson from './blueprints/velvet-crimson.json';
import bpTokyoCyber from './blueprints/tokyo-cyber.json';
import bpMiamiSunset from './blueprints/miami-sunset.json';
import bpSwissMinimal from './blueprints/swiss-minimal.json';
import bpMonarchViolet from './blueprints/monarch-violet.json';
import bpObsidianGold from './blueprints/obsidian-gold.json';
import bpHormoziBold from './blueprints/hormozi-bold.json';
import bpBeastImpact from './blueprints/beast-impact.json';
import bpViralRedline from './blueprints/viral-redline.json';
import bpCreatorHighlight from './blueprints/creator-highlight.json';
import bpGadzhiDocumentary from './blueprints/gadzhi-documentary.json';
import bpVogueEditorial from './blueprints/vogue-editorial.json';
import bpKeynoteExecutive from './blueprints/keynote-executive.json';
import bpVoxExplainer from './blueprints/vox-explainer.json';
import bpNordicClean from './blueprints/nordic-clean.json';
import bpSpatialGlass from './blueprints/spatial-glass.json';
import bpIsometricCube from './blueprints/isometric-cube.json';
import bpSynthwave80s from './blueprints/synthwave-80s.json';
import bpHudTelemetry from './blueprints/hud-telemetry.json';

export const ADVANCED_STYLE_BLUEPRINTS: Record<string, AdvancedStyleBlueprint> = {
  'dynamic-punch': bpDynamicPunch as unknown as AdvancedStyleBlueprint,
  'depth-3d-text': bpDepth3DText as unknown as AdvancedStyleBlueprint,
  'dubai-gold': bpDubaiGold as unknown as AdvancedStyleBlueprint,
  'neon-kinetic': bpNeonKinetic as unknown as AdvancedStyleBlueprint,
  'prism-pro': bpPrismPro as unknown as AdvancedStyleBlueprint,
  'paper-ii': bpPaperII as unknown as AdvancedStyleBlueprint,
  'elevate-script': bpElevateScript as unknown as AdvancedStyleBlueprint,
  'platinum-penthouse': bpPlatinumPenthouse as unknown as AdvancedStyleBlueprint,
  'royal-emerald': bpRoyalEmerald as unknown as AdvancedStyleBlueprint,
  'silver-chrome': bpSilverChrome as unknown as AdvancedStyleBlueprint,
  'velvet-crimson': bpVelvetCrimson as unknown as AdvancedStyleBlueprint,
  'tokyo-cyber': bpTokyoCyber as unknown as AdvancedStyleBlueprint,
  'miami-sunset': bpMiamiSunset as unknown as AdvancedStyleBlueprint,
  'swiss-minimal': bpSwissMinimal as unknown as AdvancedStyleBlueprint,
  'monarch-violet': bpMonarchViolet as unknown as AdvancedStyleBlueprint,
  'obsidian-gold': bpObsidianGold as unknown as AdvancedStyleBlueprint,
  'hormozi-bold': bpHormoziBold as unknown as AdvancedStyleBlueprint,
  'beast-impact': bpBeastImpact as unknown as AdvancedStyleBlueprint,
  'viral-redline': bpViralRedline as unknown as AdvancedStyleBlueprint,
  'creator-highlight': bpCreatorHighlight as unknown as AdvancedStyleBlueprint,
  'gadzhi-documentary': bpGadzhiDocumentary as unknown as AdvancedStyleBlueprint,
  'vogue-editorial': bpVogueEditorial as unknown as AdvancedStyleBlueprint,
  'keynote-executive': bpKeynoteExecutive as unknown as AdvancedStyleBlueprint,
  'vox-explainer': bpVoxExplainer as unknown as AdvancedStyleBlueprint,
  'nordic-clean': bpNordicClean as unknown as AdvancedStyleBlueprint,
  'spatial-glass': bpSpatialGlass as unknown as AdvancedStyleBlueprint,
  'isometric-cube': bpIsometricCube as unknown as AdvancedStyleBlueprint,
  'synthwave-80s': bpSynthwave80s as unknown as AdvancedStyleBlueprint,
  'hud-telemetry': bpHudTelemetry as unknown as AdvancedStyleBlueprint,
};

// Legacy compatibility interface
export type StyleBlueprint = {
  id: TypographyStyleId;
  name: string;
  fontFamily: string;
  heroFontWeight: number;
  leadFontWeight: number;
  textColor: string;
  accentColor: string;
  secondaryAccentColor: string;
  maxWordsPerChunk: number;
  kenBurnsIntensity: number;
  colorGrade: {
    name: string;
    filter: string;
  };
  animationPreset: string;
  animation: {
    mass: number;
    damping: number;
    stiffness: number;
    scaleEntrance: [number, number];
    blurEntrance: [number, number];
    opacityEntrance?: [number, number];
    [key: string]: any;
  };
  [key: string]: any;
};

export const STYLE_BLUEPRINTS: Record<string, StyleBlueprint> = {
  'dynamic-punch': {
    id: 'dynamic-punch',
    name: 'Dynamic Punch',
    fontFamily: 'Montserrat',
    heroFontWeight: 900,
    leadFontWeight: 800,
    textColor: '#FFFFFF',
    accentColor: '#38BDF8',
    secondaryAccentColor: '#FDE047',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.04,
    colorGrade: { name: 'High Contrast Vibrant', filter: 'contrast(1.15) saturate(1.2)' },
    animationPreset: 'slam',
    animation: {
      mass: 0.35,
      damping: 12,
      stiffness: 220,
      scaleEntrance: [0.68, 1.0],
      blurEntrance: [6, 0],
    },
  },
  'depth-3d-text': {
    id: 'depth-3d-text',
    name: '3D Depth & Pill',
    fontFamily: 'Plus Jakarta Sans',
    heroFontWeight: 900,
    leadFontWeight: 700,
    textColor: '#FFFFFF',
    accentColor: '#FACC15',
    secondaryAccentColor: '#38BDF8',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.03,
    colorGrade: { name: 'Modern Crisp', filter: 'contrast(1.08) saturate(1.1)' },
    animationPreset: 'pop',
    animation: {
      mass: 0.45,
      damping: 14,
      stiffness: 190,
      scaleEntrance: [0.85, 1.0],
      blurEntrance: [4, 0],
    },
  },
  'dubai-gold': {
    id: 'dubai-gold',
    name: 'Dubai 24k Gold',
    fontFamily: 'Cinzel',
    heroFontWeight: 900,
    leadFontWeight: 600,
    textColor: '#FFFFFF',
    accentColor: '#EAB308',
    secondaryAccentColor: '#CA8A04',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.02,
    colorGrade: { name: 'Warm Golden Luxury', filter: 'contrast(1.1) brightness(1.04) sepia(0.08)' },
    animationPreset: 'scale-snap',
    animation: {
      mass: 0.45,
      damping: 14,
      stiffness: 180,
      scaleEntrance: [0.9, 1.0],
      blurEntrance: [4, 0],
    },
  },
  'neon-kinetic': {
    id: 'neon-kinetic',
    name: 'Neon Cyber Motion',
    fontFamily: 'Syne',
    heroFontWeight: 900,
    leadFontWeight: 800,
    textColor: '#FFFFFF',
    accentColor: '#22D3EE',
    secondaryAccentColor: '#F43F5E',
    maxWordsPerChunk: 2,
    kenBurnsIntensity: 0.05,
    colorGrade: { name: 'Cyber Neon Glow', filter: 'contrast(1.2) saturate(1.3)' },
    animationPreset: 'slam',
    animation: {
      mass: 0.35,
      damping: 11,
      stiffness: 240,
      scaleEntrance: [0.75, 1.0],
      blurEntrance: [8, 0],
    },
  },
  'prism-pro': {
    id: 'prism-pro',
    name: 'Prism Pro',
    fontFamily: 'Plus Jakarta Sans',
    heroFontWeight: 800,
    leadFontWeight: 700,
    textColor: '#F8FAFC',
    accentColor: '#38BDF8',
    secondaryAccentColor: '#818CF8',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.03,
    colorGrade: { name: 'Cool Glass Crisp', filter: 'contrast(1.12) brightness(1.02)' },
    animationPreset: 'pop',
    animation: {
      mass: 0.45,
      damping: 14,
      stiffness: 200,
      scaleEntrance: [0.88, 1.0],
      blurEntrance: [6, 0],
    },
  },
  'paper-ii': {
    id: 'paper-ii',
    name: 'Paper II Collage',
    fontFamily: 'Montserrat',
    heroFontWeight: 900,
    leadFontWeight: 700,
    textColor: '#0F172A',
    accentColor: '#FEF08A',
    secondaryAccentColor: '#F87171',
    maxWordsPerChunk: 2,
    kenBurnsIntensity: 0.04,
    colorGrade: { name: 'Raw Film Matte', filter: 'contrast(1.1) saturate(0.95)' },
    animationPreset: 'slam',
    animation: {
      mass: 0.3,
      damping: 10,
      stiffness: 240,
      scaleEntrance: [0.65, 1.0],
      blurEntrance: [2, 0],
    },
  },
  'elevate-script': {
    id: 'elevate-script',
    name: 'Elevate Script & Real Estate Luxury',
    fontFamily: 'Playfair Display',
    heroFontWeight: 700,
    leadFontWeight: 600,
    textColor: '#FFFFFF',
    accentColor: '#F5D061',
    secondaryAccentColor: '#C99700',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.02,
    colorGrade: { name: 'Warm Luxury Editorial', filter: 'contrast(1.08) brightness(1.03) saturate(1.1)' },
    animationPreset: 'scale-snap',
    animation: {
      mass: 0.45,
      damping: 14,
      stiffness: 190,
      scaleEntrance: [0.9, 1.0],
      blurEntrance: [6, 0],
    },
  },
  'platinum-penthouse': {
    id: 'platinum-penthouse',
    name: 'Platinum Estate',
    fontFamily: 'Cinzel',
    heroFontWeight: 700,
    leadFontWeight: 600,
    textColor: '#F8FAFC',
    accentColor: '#E2E8F0',
    secondaryAccentColor: '#94A3B8',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.02,
    colorGrade: { name: 'Monochrome Platinum High-End', filter: 'contrast(1.2) grayscale(0.2)' },
    animationPreset: 'rise',
    animation: {
      mass: 0.65,
      damping: 18,
      stiffness: 130,
      scaleEntrance: [0.95, 1.0],
      blurEntrance: [6, 0],
    },
  },
  'royal-emerald': {
    id: 'royal-emerald',
    name: 'Royal Emerald',
    fontFamily: 'Plus Jakarta Sans',
    heroFontWeight: 900,
    leadFontWeight: 600,
    textColor: '#FFFFFF',
    accentColor: '#10B981',
    secondaryAccentColor: '#FCD34D',
    maxWordsPerChunk: 2,
    kenBurnsIntensity: 0.03,
    colorGrade: { name: 'Deep Emerald Luxury', filter: 'contrast(1.15) saturate(1.15)' },
    animationPreset: 'pop',
    animation: {
      mass: 0.45,
      damping: 14,
      stiffness: 180,
      scaleEntrance: [0.88, 1.0],
      blurEntrance: [4, 0],
    },
  },
  'silver-chrome': {
    id: 'silver-chrome',
    name: 'Silver Chrome',
    fontFamily: 'Oswald',
    heroFontWeight: 900,
    leadFontWeight: 700,
    textColor: '#FFFFFF',
    accentColor: '#CBD5E1',
    secondaryAccentColor: '#94A3B8',
    maxWordsPerChunk: 2,
    kenBurnsIntensity: 0.04,
    colorGrade: { name: 'Metallic Chrome Precision', filter: 'contrast(1.25) brightness(1.05)' },
    animationPreset: 'slam',
    animation: {
      mass: 0.38,
      damping: 12,
      stiffness: 220,
      scaleEntrance: [0.7, 1.0],
      blurEntrance: [4, 0],
    },
  },
  'velvet-crimson': {
    id: 'velvet-crimson',
    name: 'Velvet Crimson & Rose Gold',
    fontFamily: 'Playfair Display',
    heroFontWeight: 900,
    leadFontWeight: 600,
    textColor: '#FFF1F2',
    accentColor: '#FB7185',
    secondaryAccentColor: '#E11D48',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.02,
    colorGrade: { name: 'Deep Velvet Crimson', filter: 'contrast(1.12) brightness(1.03) saturate(1.15)' },
    animationPreset: 'scale-snap',
    animation: {
      mass: 0.45,
      damping: 14,
      stiffness: 190,
      scaleEntrance: [0.9, 1.0],
      blurEntrance: [5, 0],
    },
  },
  'tokyo-cyber': {
    id: 'tokyo-cyber',
    name: 'Tokyo Cyber Neon',
    fontFamily: 'Syne',
    heroFontWeight: 900,
    leadFontWeight: 800,
    textColor: '#DCFCE7',
    accentColor: '#4ADE80',
    secondaryAccentColor: '#22C55E',
    maxWordsPerChunk: 2,
    kenBurnsIntensity: 0.05,
    colorGrade: { name: 'Matrix Terminal Glow', filter: 'contrast(1.22) saturate(1.35)' },
    animationPreset: 'slam',
    animation: {
      mass: 0.35,
      damping: 12,
      stiffness: 240,
      scaleEntrance: [0.75, 1.0],
      blurEntrance: [6, 0],
    },
  },
  'miami-sunset': {
    id: 'miami-sunset',
    name: 'Miami Sunset Kinetic',
    fontFamily: 'Montserrat',
    heroFontWeight: 900,
    leadFontWeight: 800,
    textColor: '#FFFBEB',
    accentColor: '#F43F5E',
    secondaryAccentColor: '#FBBF24',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.04,
    colorGrade: { name: 'Vibrant Sunset Horizon', filter: 'contrast(1.18) saturate(1.3)' },
    animationPreset: 'slam',
    animation: {
      mass: 0.38,
      damping: 11,
      stiffness: 230,
      scaleEntrance: [0.72, 1.0],
      blurEntrance: [6, 0],
    },
  },
  'swiss-minimal': {
    id: 'swiss-minimal',
    name: 'Swiss Bauhaus Studio',
    fontFamily: 'Inter',
    heroFontWeight: 900,
    leadFontWeight: 500,
    textColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    secondaryAccentColor: '#A1A1AA',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.02,
    colorGrade: { name: 'Stark Monochrome Modern', filter: 'contrast(1.15) brightness(1.02)' },
    animationPreset: 'rise',
    animation: {
      mass: 0.55,
      damping: 16,
      stiffness: 160,
      scaleEntrance: [0.94, 1.0],
      blurEntrance: [5, 0],
    },
  },
  'monarch-violet': {
    id: 'monarch-violet',
    name: 'Monarch Amethyst & Gold',
    fontFamily: 'Cinzel',
    heroFontWeight: 900,
    leadFontWeight: 700,
    textColor: '#F3E8FF',
    accentColor: '#C084FC',
    secondaryAccentColor: '#FACC15',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.03,
    colorGrade: { name: 'Deep Amethyst Luxury', filter: 'contrast(1.14) saturate(1.2)' },
    animationPreset: 'scale-snap',
    animation: {
      mass: 0.48,
      damping: 15,
      stiffness: 175,
      scaleEntrance: [0.88, 1.0],
      blurEntrance: [5, 0],
    },
  },
  'obsidian-gold': {
    id: 'obsidian-gold',
    name: 'Obsidian Noir & 3D Gold Extrusion',
    fontFamily: 'Plus Jakarta Sans',
    heroFontWeight: 900,
    leadFontWeight: 800,
    textColor: '#FFFFFF',
    accentColor: '#EAB308',
    secondaryAccentColor: '#FDE047',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.03,
    colorGrade: { name: 'High Contrast 3D Bevel', filter: 'contrast(1.16) saturate(1.15)' },
    animationPreset: 'pop',
    animation: {
      mass: 0.42,
      damping: 13,
      stiffness: 200,
      scaleEntrance: [0.82, 1.0],
      blurEntrance: [5, 0],
    },
  },
  'hormozi-bold': {
    id: 'hormozi-bold',
    name: 'Hormozi Bold Punch',
    fontFamily: 'Montserrat',
    heroFontWeight: 900,
    leadFontWeight: 900,
    textColor: '#FFFFFF',
    accentColor: '#FACC15',
    secondaryAccentColor: '#4ADE80',
    maxWordsPerChunk: 2,
    kenBurnsIntensity: 0.05,
    colorGrade: { name: 'High Contrast Punch', filter: 'contrast(1.2) saturate(1.25)' },
    animationPreset: 'slam',
    animation: {
      mass: 0.3,
      damping: 10,
      stiffness: 280,
      scaleEntrance: [0.65, 1.0],
      blurEntrance: [4, 0],
    },
  },
  'beast-impact': {
    id: 'beast-impact',
    name: 'Beast Impact Pop',
    fontFamily: 'Bebas Neue',
    heroFontWeight: 900,
    leadFontWeight: 800,
    textColor: '#FFFFFF',
    accentColor: '#38BDF8',
    secondaryAccentColor: '#F43F5E',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.04,
    colorGrade: { name: 'Vibrant Comic Pop', filter: 'contrast(1.22) saturate(1.3)' },
    animationPreset: 'pop',
    animation: {
      mass: 0.35,
      damping: 11,
      stiffness: 250,
      scaleEntrance: [0.6, 1.05],
      blurEntrance: [5, 0],
    },
  },
  'viral-redline': {
    id: 'viral-redline',
    name: 'Viral Breaking Alert',
    fontFamily: 'Montserrat',
    heroFontWeight: 900,
    leadFontWeight: 800,
    textColor: '#FFFFFF',
    accentColor: '#EF4444',
    secondaryAccentColor: '#FCA5A5',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.04,
    colorGrade: { name: 'Urgent Alert Contrast', filter: 'contrast(1.25) saturate(1.2)' },
    animationPreset: 'slam',
    animation: {
      mass: 0.36,
      damping: 12,
      stiffness: 230,
      scaleEntrance: [0.72, 1.0],
      blurEntrance: [5, 0],
    },
  },
  'creator-highlight': {
    id: 'creator-highlight',
    name: 'Creator Highlighter',
    fontFamily: 'Plus Jakarta Sans',
    heroFontWeight: 800,
    leadFontWeight: 600,
    textColor: '#0F172A',
    accentColor: '#FACC15',
    secondaryAccentColor: '#FEF08A',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.02,
    colorGrade: { name: 'Warm Creator Glow', filter: 'contrast(1.08) brightness(1.02)' },
    animationPreset: 'rise',
    animation: {
      mass: 0.45,
      damping: 15,
      stiffness: 180,
      scaleEntrance: [0.92, 1.0],
      blurEntrance: [4, 0],
    },
  },
  'gadzhi-documentary': {
    id: 'gadzhi-documentary',
    name: 'Gadzhi Documentary',
    fontFamily: 'Cinzel',
    heroFontWeight: 900,
    leadFontWeight: 700,
    textColor: '#F8FAFC',
    accentColor: '#F59E0B',
    secondaryAccentColor: '#D97706',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.03,
    colorGrade: { name: 'Rich Documentary Warmth', filter: 'contrast(1.15) brightness(1.02) saturate(1.1)' },
    animationPreset: 'rise',
    animation: {
      mass: 0.55,
      damping: 16,
      stiffness: 160,
      scaleEntrance: [0.92, 1.0],
      blurEntrance: [6, 0],
    },
  },
  'vogue-editorial': {
    id: 'vogue-editorial',
    name: 'Vogue High-Fashion',
    fontFamily: 'Bodoni Moda',
    heroFontWeight: 900,
    leadFontWeight: 500,
    textColor: '#FFFFFF',
    accentColor: '#F43F5E',
    secondaryAccentColor: '#FDA4AF',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.02,
    colorGrade: { name: 'High Fashion Contrast', filter: 'contrast(1.28) saturate(1.05)' },
    animationPreset: 'rise',
    animation: {
      mass: 0.5,
      damping: 15,
      stiffness: 170,
      scaleEntrance: [0.94, 1.0],
      blurEntrance: [5, 0],
    },
  },
  'keynote-executive': {
    id: 'keynote-executive',
    name: 'Keynote Executive',
    fontFamily: 'Inter',
    heroFontWeight: 800,
    leadFontWeight: 600,
    textColor: '#FFFFFF',
    accentColor: '#38BDF8',
    secondaryAccentColor: '#94A3B8',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.02,
    colorGrade: { name: 'Clean Modern Studio', filter: 'contrast(1.1) brightness(1.02)' },
    animationPreset: 'rise',
    animation: {
      mass: 0.48,
      damping: 16,
      stiffness: 170,
      scaleEntrance: [0.95, 1.0],
      blurEntrance: [4, 0],
    },
  },
  'vox-explainer': {
    id: 'vox-explainer',
    name: 'Vox Motion Explainer',
    fontFamily: 'Oswald',
    heroFontWeight: 900,
    leadFontWeight: 700,
    textColor: '#0F172A',
    accentColor: '#EAB308',
    secondaryAccentColor: '#FDE047',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.03,
    colorGrade: { name: 'Crisp Editorial Contrast', filter: 'contrast(1.18) saturate(1.1)' },
    animationPreset: 'pop',
    animation: {
      mass: 0.38,
      damping: 13,
      stiffness: 210,
      scaleEntrance: [0.85, 1.0],
      blurEntrance: [4, 0],
    },
  },
  'nordic-clean': {
    id: 'nordic-clean',
    name: 'Nordic Studio Sans',
    fontFamily: 'Outfit',
    heroFontWeight: 700,
    leadFontWeight: 500,
    textColor: '#F8FAFC',
    accentColor: '#94A3B8',
    secondaryAccentColor: '#64748B',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.02,
    colorGrade: { name: 'Muted Architectural Slate', filter: 'contrast(1.1) brightness(1.02)' },
    animationPreset: 'rise',
    animation: {
      mass: 0.52,
      damping: 16,
      stiffness: 160,
      scaleEntrance: [0.96, 1.0],
      blurEntrance: [4, 0],
    },
  },
  'spatial-glass': {
    id: 'spatial-glass',
    name: 'Spatial Vision Glass',
    fontFamily: 'Plus Jakarta Sans',
    heroFontWeight: 900,
    leadFontWeight: 700,
    textColor: '#FFFFFF',
    accentColor: '#60A5FA',
    secondaryAccentColor: '#93C5FD',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.03,
    colorGrade: { name: 'Spatial Glass Contrast', filter: 'contrast(1.14) saturate(1.12)' },
    animationPreset: 'pop',
    animation: {
      mass: 0.44,
      damping: 14,
      stiffness: 190,
      scaleEntrance: [0.88, 1.0],
      blurEntrance: [5, 0],
    },
  },
  'isometric-cube': {
    id: 'isometric-cube',
    name: 'Isometric 3D Extrusion',
    fontFamily: 'Montserrat',
    heroFontWeight: 900,
    leadFontWeight: 800,
    textColor: '#FFFFFF',
    accentColor: '#8B5CF6',
    secondaryAccentColor: '#A78BFA',
    maxWordsPerChunk: 2,
    kenBurnsIntensity: 0.04,
    colorGrade: { name: '3D Extrusion Shadow', filter: 'contrast(1.22) saturate(1.2)' },
    animationPreset: 'pop',
    animation: {
      mass: 0.4,
      damping: 12,
      stiffness: 220,
      scaleEntrance: [0.75, 1.0],
      blurEntrance: [5, 0],
    },
  },
  'synthwave-80s': {
    id: 'synthwave-80s',
    name: '80s Synthwave Outrun',
    fontFamily: 'Syne',
    heroFontWeight: 900,
    leadFontWeight: 800,
    textColor: '#FDF4FF',
    accentColor: '#EC4899',
    secondaryAccentColor: '#06B6D4',
    maxWordsPerChunk: 3,
    kenBurnsIntensity: 0.05,
    colorGrade: { name: 'Vibrant Neon Synthwave', filter: 'contrast(1.24) saturate(1.35)' },
    animationPreset: 'slam',
    animation: {
      mass: 0.36,
      damping: 12,
      stiffness: 240,
      scaleEntrance: [0.7, 1.0],
      blurEntrance: [6, 0],
    },
  },
  'hud-telemetry': {
    id: 'hud-telemetry',
    name: 'Tactical HUD Telemetry',
    fontFamily: 'Syne',
    heroFontWeight: 900,
    leadFontWeight: 700,
    textColor: '#E0F2FE',
    accentColor: '#0EA5E9',
    secondaryAccentColor: '#0284C7',
    maxWordsPerChunk: 2,
    kenBurnsIntensity: 0.04,
    colorGrade: { name: 'Sci-Fi HUD Scanner', filter: 'contrast(1.25) saturate(1.3)' },
    animationPreset: 'pop',
    animation: {
      mass: 0.34,
      damping: 12,
      stiffness: 250,
      scaleEntrance: [0.8, 1.0],
      blurEntrance: [4, 0],
    },
  },
};

export function getStyleBlueprint(styleId?: string): StyleBlueprint {
  if (styleId && STYLE_BLUEPRINTS[styleId]) {
    return STYLE_BLUEPRINTS[styleId];
  }
  return STYLE_BLUEPRINTS['dynamic-punch'];
}

/**
 * Loads an AdvancedStyleBlueprint from static registry or disk
 */
export function getAdvancedStyleBlueprint(styleId?: string): AdvancedStyleBlueprint | null {
  const targetId = styleId || 'dynamic-punch';
  return ADVANCED_STYLE_BLUEPRINTS[targetId] || ADVANCED_STYLE_BLUEPRINTS['dynamic-punch'] || null;
}
