import type { TypographyStyleId } from './types';

export type TypographyCategory = 'kinetic' | 'depth' | 'minimal' | 'real-estate';
export type TypographyWordTimestamp = { word: string; start: number; end: number };

export type TypographyStyle = {
  id: string;
  name: string;
  tag: string;
  category: TypographyCategory;
  description: string;
  videoSrc: string;
  posterSrc: string;
  accentColor: string;
  tags: string[];
  transcriptText: string;
  duration: number;
  words: TypographyWordTimestamp[];
};

export const TYPOGRAPHY_STYLES: TypographyStyle[] = [
  { id: 'vox-giant-stagger', name: 'Vox Typography Stagger', tag: 'High-Impact Vox', category: 'kinetic', description: 'Staggered multi-line slam with orange tape highlights', videoSrc: '', posterSrc: '', accentColor: '#FF6D00', tags: ['Vox', 'Stagger'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'kinetic-marquee-diagonal', name: 'Diagonal Marquee Flow', tag: 'Ticker Stream', category: 'kinetic', description: '12-degree tilted continuous marquee text flow', videoSrc: '', posterSrc: '', accentColor: '#FF6D00', tags: ['Marquee', 'Stream'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'multi-line-block-slam', name: 'Brutalist Block Slam', tag: 'Brutalist', category: 'kinetic', description: 'Spring physics multi-row stacked block slam', videoSrc: '', posterSrc: '', accentColor: '#FFA726', tags: ['Block', 'Slam'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'headliner', name: 'Headliner Bold Impact', tag: 'Impact Punch', category: 'kinetic', description: 'Bold headline pop with heavy outline stroke', videoSrc: '', posterSrc: '', accentColor: '#FF6D00', tags: ['Impact', 'Headliner'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'action', name: 'Action Magazine Punch', tag: 'Action Red', category: 'kinetic', description: 'High-energy magazine punch cuts and rotations', videoSrc: '', posterSrc: '', accentColor: '#EF4444', tags: ['Action', 'Magazine'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'boxing-punch-heavy', name: 'Heavyweight Slam', tag: 'Heavyweight', category: 'kinetic', description: 'Impact ripple slam with dark card overlay', videoSrc: '', posterSrc: '', accentColor: '#EF4444', tags: ['Boxing', 'Heavy'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'bold-ticker-news', name: 'Breaking News Ticker', tag: 'News Ticker', category: 'minimal', description: 'Horizontal ticker stream with lower third bar', videoSrc: '', posterSrc: '', accentColor: '#FF9100', tags: ['News', 'Ticker'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'the-difference', name: 'The Difference Contrast', tag: 'Contrast Flip', category: 'minimal', description: 'Teal/purple contrast flip with zoom', videoSrc: '', posterSrc: '', accentColor: '#C084FC', tags: ['Difference', 'Contrast'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'hormozi-bold', name: 'Hormozi Kinetic Pop', tag: 'Viral Pop', category: 'kinetic', description: 'Viral yellow box pop with emoji integration', videoSrc: '', posterSrc: '', accentColor: '#FFD600', tags: ['Hormozi', 'Pop'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'viral-redline', name: 'Viral Redline Box', tag: 'Redline Border', category: 'kinetic', description: 'Spring snap box with thick crimson border', videoSrc: '', posterSrc: '', accentColor: '#FF3D00', tags: ['Viral', 'Redline'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'apple-keynote-punch', name: 'Apple Keynote Punch', tag: 'Keynote Minimal', category: 'minimal', description: 'Spotlight scale push with dark canvas', videoSrc: '', posterSrc: '', accentColor: '#FFFFFF', tags: ['Apple', 'Keynote'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'editorial-magazine-manifesto', name: 'Editorial Manifesto', tag: 'High-Fashion Editorial', category: 'minimal', description: 'Playfair Display magazine manifesto reveal', videoSrc: '', posterSrc: '', accentColor: '#F8FAFC', tags: ['Editorial', 'Manifesto'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'minimal-swiss-clean', name: 'Ultra Minimal Swiss Grid', tag: 'Swiss Grid', category: 'minimal', description: 'Clean coordinate slide with Swiss grid overlay', videoSrc: '', posterSrc: '', accentColor: '#E2E8F0', tags: ['Swiss', 'Clean'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'cursive', name: 'Cursive Elegance', tag: 'Caveat Script', category: 'minimal', description: 'Organic cursive script flow reveal', videoSrc: '', posterSrc: '', accentColor: '#FFA726', tags: ['Cursive', 'Script'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'chalk', name: 'Chalk Doodle Notes', tag: 'Chalk Monospace', category: 'minimal', description: 'Hand-drawn chalkboard note card reveal', videoSrc: '', posterSrc: '', accentColor: '#FFFDD0', tags: ['Chalk', 'Notes'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'podcast-quote-card', name: 'Podcast Quote Card', tag: 'Quote Glass', category: 'minimal', description: 'Frosted glass quote card with waveform pulse', videoSrc: '', posterSrc: '', accentColor: '#FF9100', tags: ['Podcast', 'Quote'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'floodlight', name: 'Floodlight Badge Spotlight', tag: 'Yellow Spotlight', category: 'kinetic', description: 'Centered yellow badge spotlight with scale bounce', videoSrc: '', posterSrc: '', accentColor: '#FF6D00', tags: ['Floodlight', 'Spotlight'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'storyline', name: 'Storyline Chapter Beat', tag: 'Chapter Progress', category: 'minimal', description: 'Progress line chapter bar narrative slide', videoSrc: '', posterSrc: '', accentColor: '#38BDF8', tags: ['Storyline', 'Chapter'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'blue-muse', name: 'Blue Muse Atmospheric', tag: 'Blue Glow', category: 'depth', description: 'Atmospheric blue glow with serif overlay', videoSrc: '', posterSrc: '', accentColor: '#3B82F6', tags: ['Blue', 'Glow'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'split-color-invert', name: 'Swiss Color Invert', tag: 'Inverted Split', category: 'minimal', description: 'Contrast dual-tone split card invert', videoSrc: '', posterSrc: '', accentColor: '#FFFFFF', tags: ['Split', 'Invert'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'glitch-cyber-rave', name: 'Glitch Cyber HUD', tag: 'Cyber Glitch', category: 'depth', description: 'RGB split channel glitch with HUD telemetry frame', videoSrc: '', posterSrc: '', accentColor: '#00E5FF', tags: ['Glitch', 'Cyber'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'isometric-3d-flythrough', name: '3D Perspective Tunnel', tag: '3D Spatial', category: 'depth', description: '3D perspective tunnel spatial camera flythrough', videoSrc: '', posterSrc: '', accentColor: '#FF6D00', tags: ['3D', 'Spatial'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'retro-synthwave', name: 'Retro 80s Synthwave', tag: 'Outrun Chrome', category: 'depth', description: 'Neon grid horizon sweep with magenta glow', videoSrc: '', posterSrc: '', accentColor: '#E040FB', tags: ['Retro', 'Synthwave'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'glow-gradient-pill', name: 'Fluid Aurora Gradient Pill', tag: 'Aurora Pill', category: 'minimal', description: 'Aurora glass capsule gradient pulse', videoSrc: '', posterSrc: '', accentColor: '#818CF8', tags: ['Aurora', 'Pill'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'cinematic-trailer', name: 'Cinematic 3D Trailer', tag: 'Blockbuster Smoke', category: 'depth', description: 'Blockbuster volumetric smoke and lens flare', videoSrc: '', posterSrc: '', accentColor: '#FFB300', tags: ['Cinematic', 'Trailer'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'gold-centre', name: 'Gold Centre 3D Metallic', tag: 'Gold Metallic', category: 'depth', description: '3D metallic gold glint sweep and zoom', videoSrc: '', posterSrc: '', accentColor: '#FFD700', tags: ['Gold', 'Metallic'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'stat-numbers', name: 'Stat Numbers & ROI', tag: 'Financial Metric', category: 'kinetic', description: 'Finance counter scale and emerald metric badge', videoSrc: '', posterSrc: '', accentColor: '#10B981', tags: ['Stat', 'Numbers'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'architectural-blueprint', name: 'Blueprint Technical Grid', tag: 'Architectural Grid', category: 'real-estate', description: 'Drafting grid callout lines and cyan blueprint', videoSrc: '', posterSrc: '', accentColor: '#00BCD4', tags: ['Blueprint', 'Grid'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'dubai-gold', name: 'Dubai 24K Gold', tag: '24K Gold Foil', category: 'real-estate', description: '24K gold foil specular sweep and luxury card', videoSrc: '', posterSrc: '', accentColor: '#FFD700', tags: ['Dubai', 'Gold'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'luxury-listing-stats', name: 'Luxury Listing Stats', tag: 'Property Spec', category: 'real-estate', description: 'Property spec badge slide and amber highlights', videoSrc: '', posterSrc: '', accentColor: '#FFA726', tags: ['Luxury', 'Stats'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'luxury-monogram', name: 'Monogram High Elegance', tag: 'Monogram Seal', category: 'real-estate', description: 'Bespoke monogram seal with gold hairline reveal', videoSrc: '', posterSrc: '', accentColor: '#F59E0B', tags: ['Monogram', 'Elegance'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'realtor-punch-quotes', name: 'Realtor Authority Quotes', tag: 'Agent Callout', category: 'real-estate', description: 'Verified agent quote badge with orange accent', videoSrc: '', posterSrc: '', accentColor: '#FF6D00', tags: ['Realtor', 'Quotes'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'platinum-penthouse', name: 'Platinum Penthouse', tag: 'Silver Chrome', category: 'real-estate', description: 'Penthouse iced chrome glass card with silver rim light', videoSrc: '', posterSrc: '', accentColor: '#E2E8F0', tags: ['Platinum', 'Penthouse'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'architectural-tour', name: 'Architectural Tour', tag: 'Dimension Draw', category: 'real-estate', description: 'Room dimension callouts and blueprint grid', videoSrc: '', posterSrc: '', accentColor: '#FFA726', tags: ['Architectural', 'Tour'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  // 8 Flagship Styles
  { id: 'depth-behind-subject', name: 'Depth Behind Subject', tag: 'Flagship · Matting Mask', category: 'depth', description: 'Subject segmentation matting mask overlay with text behind subject', videoSrc: '', posterSrc: '', accentColor: '#FF6D00', tags: ['Flagship', 'Subject'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'luxury-gold-serif', name: 'Luxury Gold Serif', tag: 'Flagship · 24K Gold Foil', category: 'minimal', description: '24K gold foil specular sweep with Cormorant / Playfair serif', videoSrc: '', posterSrc: '', accentColor: '#FFD700', tags: ['Flagship', 'Gold'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'big-small-mix', name: 'Big-Small Contrast Mix', tag: 'Flagship · Fluid Type Scale', category: 'kinetic', description: '5x hero word contrast scale mix with serif + heavy sans', videoSrc: '', posterSrc: '', accentColor: '#38BDF8', tags: ['Flagship', 'Contrast'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'parallax-layers', name: 'Multi-Layer Parallax', tag: 'Flagship · Parallax Planes', category: 'depth', description: '3-tier depth parallax camera planes with blurred background text', videoSrc: '', posterSrc: '', accentColor: '#E040FB', tags: ['Flagship', 'Parallax'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'mask-reveal-slab', name: 'Mask Reveal Slab', tag: 'Flagship · Mask Reveal', category: 'kinetic', description: 'Dynamic mask clip reveal with heavy slab typography', videoSrc: '', posterSrc: '', accentColor: '#10B981', tags: ['Flagship', 'Mask'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'camera-push-stack', name: 'Camera Push Stack', tag: 'Flagship · Camera Impulse', category: 'kinetic', description: '3D camera push and pan impulse on stacked typography rows', videoSrc: '', posterSrc: '', accentColor: '#FF3D00', tags: ['Flagship', 'Camera'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'chrome-3d-extrude', name: 'Chrome 3D Extrude', tag: 'Flagship · Metallic Extrude', category: 'depth', description: 'Stacked multi-layer 3D metallic chrome extrude shadow', videoSrc: '', posterSrc: '', accentColor: '#94A3B8', tags: ['Flagship', 'Chrome'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
  { id: 'editorial-split-serif', name: 'Editorial Split Serif', tag: 'Flagship · High-Fashion', category: 'minimal', description: 'High-fashion editorial split serif with hairline rules and grain', videoSrc: '', posterSrc: '', accentColor: '#F59E0B', tags: ['Flagship', 'Editorial'], transcriptText: 'Hello, world! This is how you GROW your business, fast.', duration: 5, words: [] },
];

export function getTypographyStyle(styleId: string): TypographyStyle | undefined {
  return TYPOGRAPHY_STYLES.find((s) => s.id === styleId) || TYPOGRAPHY_STYLES[0];
}
