/**
 * Standardized Content Test Scenarios for Style Robustness & Fidelity Validation
 *
 * Defines 8 distinct content scenarios designed to stress-test typography scaling,
 * line wrapping, multi-line hierarchy, keyword contrast, kinetic cadence, and aspect ratios.
 */

import type { ContentScenario, ContentScenarioId } from './types';

export const CONTENT_SCENARIOS: Record<ContentScenarioId, ContentScenario> = {
  'short-phrase': {
    id: 'short-phrase',
    name: 'Short Phrase (Oversized Hero)',
    description: 'Ultra-minimal 2-word phrase to test hero sizing, visual presence, and raw typography weight.',
    purpose: 'Test oversized hero typography, safe margins, and uncluttered layout.',
    text: 'Think Bigger.',
    durationSeconds: 3.0,
    words: [
      { word: 'Think', start: 0.2, end: 0.9 },
      { word: 'Bigger.', start: 1.0, end: 2.2, highlight: true },
    ],
    phrases: [
      {
        id: 'sp-1',
        leadText: 'Think',
        heroText: 'BIGGER.',
        start: 0.2,
        end: 2.8,
        highlightType: 'emphasis',
        size: 'oversized',
        position: 'center',
      },
    ],
    aspectRatios: ['9:16', '16:9', '1:1'],
  },

  'normal-sentence': {
    id: 'normal-sentence',
    name: 'Normal Sentence (Phrase-Level Flow)',
    description: 'Standard 4-word conversational sentence testing natural lead-in and core message punch.',
    purpose: 'Test baseline phrase-level composition, font pairing, and standard kinetic motion.',
    text: 'Your ideas deserve better.',
    durationSeconds: 3.5,
    words: [
      { word: 'Your', start: 0.2, end: 0.5 },
      { word: 'ideas', start: 0.55, end: 0.95 },
      { word: 'deserve', start: 1.0, end: 1.45 },
      { word: 'better.', start: 1.5, end: 2.6, highlight: true },
    ],
    phrases: [
      {
        id: 'ns-1',
        leadText: 'Your ideas',
        heroText: 'DESERVE BETTER.',
        subText: 'never settle for average',
        start: 0.2,
        end: 3.2,
        highlightType: 'emphasis',
        size: 'large',
        position: 'center',
      },
    ],
    aspectRatios: ['9:16', '16:9', '1:1'],
  },

  'long-sentence': {
    id: 'long-sentence',
    name: 'Long Sentence (Responsive Text Wrapping)',
    description: '12-word complex sentence testing text wrapping, maximum width boundaries, and multi-chunk flow.',
    purpose: 'Stress-test responsive line breaking, container overflow prevention, and multi-segment cadence.',
    text: 'Turn your content into powerful videos that people actually want to watch.',
    durationSeconds: 6.0,
    words: [
      { word: 'Turn', start: 0.2, end: 0.5 },
      { word: 'your', start: 0.55, end: 0.8 },
      { word: 'content', start: 0.85, end: 1.25 },
      { word: 'into', start: 1.3, end: 1.55 },
      { word: 'powerful', start: 1.6, end: 2.1, highlight: true },
      { word: 'videos', start: 2.15, end: 2.65 },
      { word: 'that', start: 2.75, end: 2.95 },
      { word: 'people', start: 3.0, end: 3.35 },
      { word: 'actually', start: 3.4, end: 3.85 },
      { word: 'want', start: 3.9, end: 4.2 },
      { word: 'to', start: 4.25, end: 4.45 },
      { word: 'watch.', start: 4.5, end: 5.4, highlight: true },
    ],
    phrases: [
      {
        id: 'ls-1',
        leadText: 'Turn your content into',
        heroText: 'POWERFUL VIDEOS',
        start: 0.2,
        end: 2.7,
        highlightType: 'emphasis',
        size: 'large',
        position: 'center',
      },
      {
        id: 'ls-2',
        leadText: 'that people actually',
        heroText: 'WANT TO WATCH.',
        subText: 'guaranteed retention',
        start: 2.75,
        end: 5.7,
        highlightType: 'pill',
        size: 'large',
        position: 'center',
      },
    ],
    aspectRatios: ['9:16', '16:9', '1:1'],
  },

  'multi-line': {
    id: 'multi-line',
    name: 'Multi-Line Stack (Vertical Hierarchy)',
    description: '3 sequential stacked lines testing line height, vertical rhythm, and stacked alignment.',
    purpose: 'Test stacked multi-line hierarchy, line spacing consistency, and center alignment.',
    text: 'Build your brand. Tell better stories. Grow faster.',
    durationSeconds: 5.5,
    words: [
      { word: 'Build', start: 0.2, end: 0.6 },
      { word: 'your', start: 0.65, end: 0.9 },
      { word: 'brand.', start: 0.95, end: 1.5, highlight: true },
      { word: 'Tell', start: 1.7, end: 2.0 },
      { word: 'better', start: 2.05, end: 2.4 },
      { word: 'stories.', start: 2.45, end: 3.1, highlight: true },
      { word: 'Grow', start: 3.3, end: 3.7 },
      { word: 'faster.', start: 3.75, end: 4.8, highlight: true },
    ],
    phrases: [
      {
        id: 'ml-1',
        leadText: 'STEP 1',
        heroText: 'BUILD YOUR BRAND',
        start: 0.2,
        end: 1.6,
        highlightType: 'box',
        position: 'center',
      },
      {
        id: 'ml-2',
        leadText: 'STEP 2',
        heroText: 'TELL BETTER STORIES',
        start: 1.7,
        end: 3.2,
        highlightType: 'box',
        position: 'center',
      },
      {
        id: 'ml-3',
        leadText: 'STEP 3',
        heroText: 'GROW FASTER',
        start: 3.3,
        end: 5.2,
        highlightType: 'emphasis',
        position: 'center',
      },
    ],
    aspectRatios: ['9:16', '16:9', '1:1'],
  },

  'keyword-emphasis': {
    id: 'keyword-emphasis',
    name: 'Keyword Emphasis (High Contrast)',
    description: 'Single high-impact uppercase keyword contrasting against standard conversational context words.',
    purpose: 'Test keyword contrast, glow/badge treatment, and selective scale emphasis.',
    text: 'Make your content IMPOSSIBLE to ignore.',
    durationSeconds: 4.5,
    words: [
      { word: 'Make', start: 0.2, end: 0.55 },
      { word: 'your', start: 0.6, end: 0.85 },
      { word: 'content', start: 0.9, end: 1.3 },
      { word: 'IMPOSSIBLE', start: 1.35, end: 2.4, highlight: true },
      { word: 'to', start: 2.45, end: 2.7 },
      { word: 'ignore.', start: 2.75, end: 3.8, highlight: true },
    ],
    phrases: [
      {
        id: 'ke-1',
        leadText: 'Make your content',
        heroText: 'IMPOSSIBLE',
        subText: 'to ignore.',
        start: 0.2,
        end: 4.0,
        highlightType: 'emphasis',
        emphasisWords: ['IMPOSSIBLE'],
        size: 'oversized',
        position: 'center',
      },
    ],
    aspectRatios: ['9:16', '16:9', '1:1'],
  },

  'multi-emphasis': {
    id: 'multi-emphasis',
    name: 'Multi-Emphasis (Recurring Cadence)',
    description: 'Three rapid punchy statements each with distinct accent keywords in continuous rhythm.',
    purpose: 'Test recurring accent triggers, animation resets, and rapid visual hierarchy transitions.',
    text: 'Create faster. Publish better. Grow consistently.',
    durationSeconds: 5.0,
    words: [
      { word: 'Create', start: 0.2, end: 0.6 },
      { word: 'faster.', start: 0.65, end: 1.3, highlight: true },
      { word: 'Publish', start: 1.5, end: 1.9 },
      { word: 'better.', start: 1.95, end: 2.7, highlight: true },
      { word: 'Grow', start: 2.9, end: 3.3 },
      { word: 'consistently.', start: 3.35, end: 4.4, highlight: true },
    ],
    phrases: [
      {
        id: 'me-1',
        leadText: 'Create',
        heroText: 'FASTER.',
        start: 0.2,
        end: 1.4,
        highlightType: 'emphasis',
        position: 'center',
      },
      {
        id: 'me-2',
        leadText: 'Publish',
        heroText: 'BETTER.',
        start: 1.5,
        end: 2.8,
        highlightType: 'emphasis',
        position: 'center',
      },
      {
        id: 'me-3',
        leadText: 'Grow',
        heroText: 'CONSISTENTLY.',
        start: 2.9,
        end: 4.6,
        highlightType: 'emphasis',
        position: 'center',
      },
    ],
    aspectRatios: ['9:16', '16:9', '1:1'],
  },

  'fast-rhythm': {
    id: 'fast-rhythm',
    name: 'Fast Rhythm (High-Velocity Kinetic)',
    description: 'Rapid 1-word beats fired every 0.3s testing quick spring transitions and legibility.',
    purpose: 'Test high-frequency kinetic typography, quick easing reset, and motion blur handling.',
    text: 'Speed. Precision. Impact. Dominate. Win.',
    durationSeconds: 3.5,
    words: [
      { word: 'Speed.', start: 0.1, end: 0.45, highlight: true },
      { word: 'Precision.', start: 0.5, end: 0.95, highlight: true },
      { word: 'Impact.', start: 1.0, end: 1.5, highlight: true },
      { word: 'Dominate.', start: 1.55, end: 2.1, highlight: true },
      { word: 'Win.', start: 2.15, end: 3.0, highlight: true },
    ],
    phrases: [
      { id: 'fr-1', heroText: 'SPEED', start: 0.1, end: 0.48, highlightType: 'emphasis', size: 'large', position: 'center' },
      { id: 'fr-2', heroText: 'PRECISION', start: 0.5, end: 0.98, highlightType: 'emphasis', size: 'large', position: 'center' },
      { id: 'fr-3', heroText: 'IMPACT', start: 1.0, end: 1.52, highlightType: 'emphasis', size: 'large', position: 'center' },
      { id: 'fr-4', heroText: 'DOMINATE', start: 1.55, end: 2.12, highlightType: 'emphasis', size: 'large', position: 'center' },
      { id: 'fr-5', heroText: 'WIN.', start: 2.15, end: 3.2, highlightType: 'emphasis', size: 'oversized', position: 'center' },
    ],
    aspectRatios: ['9:16', '16:9', '1:1'],
  },

  'slow-rhythm': {
    id: 'slow-rhythm',
    name: 'Slow Rhythm (Atmospheric Hold)',
    description: 'Slow, lingering 7-word phrase with 2.5s hold testing subtle micro-motion and calm elegance.',
    purpose: 'Test whether style maintains personality and elegance without relying on fast rapid motion cuts.',
    text: 'Mastery takes deep patience and quiet dedication.',
    durationSeconds: 5.5,
    words: [
      { word: 'Mastery', start: 0.3, end: 0.9 },
      { word: 'takes', start: 0.95, end: 1.35 },
      { word: 'deep', start: 1.4, end: 1.85 },
      { word: 'patience', start: 1.9, end: 2.6, highlight: true },
      { word: 'and', start: 2.65, end: 2.9 },
      { word: 'quiet', start: 2.95, end: 3.4 },
      { word: 'dedication.', start: 3.45, end: 4.8, highlight: true },
    ],
    phrases: [
      {
        id: 'sr-1',
        leadText: 'Mastery takes deep patience',
        heroText: 'AND QUIET DEDICATION.',
        subText: 'the craft of true perfection',
        start: 0.3,
        end: 5.0,
        highlightType: 'emphasis',
        size: 'large',
        position: 'center',
      },
    ],
    aspectRatios: ['9:16', '16:9', '1:1'],
  },
};

export const DEFAULT_STANDARDIZED_SCRIPT = CONTENT_SCENARIOS['normal-sentence'];
