export const HANDWRITTEN_NOTES_VISUAL_TOKENS = [
  'doodle_bank',
  'doodle_atm',
  'doodle_rupee',
  'doodle_credit_card',
  'doodle_wallet',
  'doodle_piggy_bank',
  'doodle_book',
  'doodle_pencil',
  'doodle_graduation',
  'doodle_lightbulb',
  'doodle_trophy',
  'doodle_growth',
  'doodle_chart',
  'doodle_briefcase',
  'doodle_target',
  'doodle_rocket',
  'diagram_flowchart',
  'diagram_timeline',
  'diagram_mindmap',
  'formula_box',
  'comparison_table',
  'timeline_strip',
  'document_checklist',
  'exam_date_card',
  'mind_map',
  'pros_cons_table',
  'step_ladder',
  'flowchart_box',
  'before_after_box',
  'calendar_reminder',
  'ranked_list',
  'quote_card',
  'effect_bracket',
  'effect_checkmark',
  'effect_xmark',
  'arrow_diagram',
  'highlight_swipe',
  'red_circle',
] as const;

export function handwrittenNotesRequiredPlanningOrder(renderLanguage: 'english' | 'hinglish') {
  return [
    '1. Upload: accept the user audio/video as the only source of truth.',
    '2. Transcription: keep Hindi/Urdu source transcript in the original script for accuracy, with timestamp segments and word timing when available.',
    '3. Script Details: convert the complete transcript meaning into a normal full English sourceScript only for analysis, word count, topic detection, asset reasoning, and diagram planning.',
    '4. CreativeDirector: create micro note actions from the actual 60-second script meaning. Do not add extra facts, remove facts, or rewrite the message into a different story.',
    '5. Note Action Plan: create videoUsePlan as timed note-elements: heading, one short body line, bullet, highlight, red circle, arrow, bracket, checkmark, X mark, formula box, comparison table, timeline strip, document checklist, exam date card, mind map, pros/cons table, step ladder, before/after box, calendar reminder, ranked list, quote card, or diagram only when the audio actually says that idea. Show elements one-by-one according to audio timing.',
    '6. ManagerChecklist: verify audio-text sync, no future points, one spoken point equals one note action, no old/default text, and no filler just to fill space.',
    renderLanguage === 'hinglish'
      ? '7. Render Language: only after English analysis and CreativeDirector planning, create final visible notes in Hybrid English + Hinglish: main keywords/points in English, supporting explanation in clean Roman Hinglish.'
      : '7. Render Language: keep renderText/renderBody in clean English because the source speech is English.',
  ];
}

export function handwrittenNotesSystemPromptRules(renderLanguage: 'english' | 'hinglish') {
  return [
    'HANDWRITTEN NOTES SCRIPT DETAILS:',
    'This template uses this 7-step pipeline: Upload -> Transcription -> Script Details English Analysis -> CreativeDirector Note Action Plan -> Render Language Conversion -> ManagerChecklist Validator -> Remotion Render Export.',
    'CreativeDirector replaces generic script-details behavior for this template.',
    'Analysis language is always English. Final visible notes depend on the source speech.',
    'sourceScript must be a complete normal English script/translation of the full transcript meaning.',
    'Use sourceScript for topic detection, asset reasoning, diagram planning, note structure, and videoUsePlan timing, but do not create new story content.',
    'Do not summarize the reel into new text. The script is already short. Use the same meaning, same facts, same order, and only the words/ideas actually spoken unless timing requires splitting into smaller note actions.',
    'BACKGROUND RULE: use a full off-white notebook page, not a pure white slide. Use faint notebook lines, subtle paper texture, page shadow, and slight 2-3 degree camera tilt.',
    'FRAME RULE: the whole 9:16 frame should feel like a notebook page under a moving camera, not a PowerPoint card layout. Notes can overlap and fill the page.',
    'NOTEBOOK PALETTE RULE: use only a school-notebook palette: black ink for primary headings, blue ink for secondary/body notes, red pen for corrections/warnings/circles, and yellow marker for highlights. Avoid teal/purple/gradient/mixed palettes.',
    'PAGE RULE: do not make the output look like a presentation slide with top/middle/bottom cards and huge white gaps. Notes must occupy most of the vertical frame, can overlap like real notebook layers, and should feel like a reel canvas.',
    'CAMERA RULE: plan notes so renderer can continuously move around the notebook area: slow zoom in, pan left, pan right, zoom out, then punch in on highlighted words and slightly tilt warning/X moments. Do not create static same-position note rows.',
    'DYNAMIC EFFECT RULE: use fade-ins, highlight sweeps, underline reveals, and quick transitions between note pages. Avoid long static holds unless the audio has a pause.',
    'DESIGN RULE: the reel must feel like live handwritten notes on a clean whiteboard, not a typed text animation, poster, or slideshow.',
    'NOTEBOOK FEEL RULE: final visual should feel like a student made notes by hand, not a Canva template. Prefer torn paper, sticky-note layers, marker highlights, red pen circles, hand-drawn arrows, scribbles, rough underlines, and imperfect handmade spacing.',
    'REEL DENSITY RULE: every second should have visible motion or a new focus area. Avoid large empty white space between notes; use big handwriting, overlap, arrows, underlines, and camera movement to keep attention.',
    'HIERARCHY RULE: do not make every note/card the same size. Use a clear reel hierarchy: BIG HOOK, then medium main point, then smaller supporting note. Structured moments and the active spoken idea should be visually larger than older/supporting notes.',
    'FONT HIERARCHY RULE: headings should feel like handwritten marker text, but supporting explanation/body must be clean readable sans-serif. Do not make every line the same handwritten font.',
    'ACTIVE FOCUS RULE: every moment needs exactly one hero element for the viewer to look at. Older notes may stay visible but should feel secondary. Plan beats like: BIG QUESTION -> marker swipe -> red circle -> arrow/cause -> checkmark/answer. Never reveal multiple equally important lines at once.',
    'WRITING RULE: text should be planned as one handwritten write-on action at a time. Highlight/underline/red circle/arrow should appear only after the related text is written.',
    'ANIMATION RULE: plan for fast smooth handwriting, not slow subtitles. Each short title should finish writing quickly, then the effect/highlight/checkmark should land on the audio beat.',
    'MOTION LANGUAGE RULE: handwritten notes reels need visible motion primitives: marker draw animation, underline draw, red circle draw, arrow draw, notebook page flip, paper slide, stamp effect, and checkbox tick effect. Choose the primitive that matches the spoken beat.',
    'VIRAL NOTES ELEMENT RULE: use visible yellow highlighter, red correction marks, exam-style ticks, arrows, boxes, side notes, circled keywords, and ranking numbers frequently enough that the reel feels like modern study notes. These elements must support the current spoken point.',
    'VIRAL REEL FORMULA: every 3-4 seconds repeat this cycle when possible: new note card, highlight swipe, red circle, tick mark, arrow, zoom. This is the default motion grammar for handwritten notes reels.',
    'DRAWING EFFECT RULE: use bracket/checkmark/X/highlight/circle only for meaning, not decoration. Bracket groups documents/process steps; checkmark marks completed/action/practice points; X mark marks mistake/avoid/wrong action; highlight marks one critical keyword/date/amount; circle marks dates, deadlines, fees, salary, result, or warning only.',
    'DRAWING TIMING RULE: drawing effects must appear after the related title/body is written. Never draw an effect before the matching spoken point.',
    'PAGE LABEL RULE: do not request visible page numbers. If a page changes, the transition itself is enough.',
    'READABILITY RULE: plan large mobile-readable note blocks. Main heading should be short and bold; section headings 3-6 words; body max 8-10 words.',
    'LESS TEXT RULE: visible notes should feel like visual notes, not subtitles. Prefer 1 strong line per beat. renderText max 5-6 words; renderBody max 0-6 words unless a checklist/table truly needs it.',
    'DRAMATIC HOOK RULE: first 2 seconds must be a bold question or problem statement, e.g. "Response nahi mil raha?", with strong underline/highlight/red question energy. Do not start with a generic title.',
    'EMPHASIS RULE: do not use yellow highlight on every heading. Use yellow only for main heading or critical keyword. Prefer teal heading text, navy body text, and burgundy warning/date text over extra shapes.',
    'EFFECT SELECTION RULE: use effect_bracket visual for grouped documents/requirements; effect_checkmark for do/apply/download/practice/submit actions; effect_xmark for warnings/mistakes/avoid; highlight_swipe for one key term; red_circle for exact date/deadline/amount/warning.',
    'SKETCH DRAWING RULE: avoid small circle badges such as !, 11, or decorative icon+line. Use hand-drawn sketch objects when they clearly explain the current point, such as exam paper for exams, RBI office/building for RBI or banking, admit card sheet for admit card, calendar sheet for dates, payment slip for fee/salary, or practice sheet for mock tests.',
    renderLanguage === 'hinglish'
      ? 'For Hindi/Urdu/Hinglish source audio, final visible notes must use Hybrid English + Hinglish after English planning is complete.'
      : 'For English source audio, renderText and renderBody must stay clean English.',
    renderLanguage === 'hinglish'
      ? 'Hybrid formula: renderText should prefer standard English keywords/titles such as Admit Card, Exam Date, Documents, Mock Tests, Salary, Benefits, Apply, Download, Selection, Training. renderBody should be short natural Hinglish such as "April first week me expected hai" or "Regular practice continue rakho".'
      : 'English formula: renderText should be a short English keyword/title and renderBody should be concise English support text.',
    renderLanguage === 'hinglish'
      ? 'HINGLISH STYLE RULE: renderBody must sound like natural creator Hinglish, not literal translation. Prefer "Response nahi mil raha?", "Aaj skills bhi zaroori hain", "Strong skills wale candidates", "Resume ko better banate raho", "Rejection se seekho", "Mehnat continue rakho". Avoid awkward phrases like "skill add karo" when "naya skill seekho" is clearer.'
      : 'STYLE RULE: renderBody should sound like natural study notes, not a robotic subtitle.',
    renderLanguage === 'hinglish'
      ? 'Do not convert standard English terms into phonetic Hinglish. Keep official names, exam names, dates, amounts, websites, document names, and finance/job keywords in English.'
      : 'Keep official names, dates, amounts, websites, document names, and finance/job keywords in English.',
    renderLanguage === 'hinglish'
      ? 'Good examples: renderText "Admit Card", renderBody "April first week me expected hai"; renderText "Exam Date", renderBody "11 April ko exam hai"; renderText "Mock Tests", renderBody "Daily practice zaroori hai".'
      : 'Good examples: renderText "Admit Card", renderBody "Expected in the first week of April"; renderText "Exam Date", renderBody "The exam is on 11 April".',
    'Never plan directly from phonetic Hindi/Urdu transcription. Never output broken words such as painkaard, apalaaee, naheen, dokumaints.',
    'Every videoUsePlan item must correspond to the actual transcript timing and meaning. Audio-text match is mandatory. Do not use old fallback/default demo text.',
    'IMPORTANT SYNC RULE: do not write future points before the speaker says them. Only write the current spoken meaning.',
    'If the speaker says one point, write one short note action. Do not show future points early and do not show supporting facts that are not being spoken in that time window.',
    'If the screen is still mostly empty after the heading, prefer increasing note size or adding one useful underline, red circle, arrow, revision box, or hand-drawn sketch tied to the current spoken point. Do not add unrelated bullets or small circle badges.',
    'Do not plan future audio points early. Every title/body must appear at or after its spoken timestamp.',
    'One videoUsePlan item must equal one note element/writing action only.',
    'Plan scenes according to what the audio is saying at that moment. Scene 1 and Scene 2 can share the same page, but the next note element must appear only when the audio reaches that idea.',
    'Allowed note elements: Main Heading, Subheading, Bullet 1, Bullet 2, Highlight, Red Circle, Arrow, Bracket, Checkmark, X Mark, Flowchart, Timeline, Mind Map, Formula Box, Comparison Table, Timeline Strip, Document Checklist, Exam Date Card, Pros/Cons Table, Step Ladder, Before/After Box, Calendar Reminder, Ranked List, Quote Card, Underline, Revision Box.',
    'SCENE TYPE RULE: choose visual "formula_box" for formulas/fees/calculations/eligibility equations; "comparison_table" for before-vs-after, yes-vs-no, option A vs option B; "timeline_strip" for sequence/date/month/year/order; "document_checklist" for required documents/uploads/ID proofs; "exam_date_card" for exam date, admit card date, deadline, result date, or important date.',
    'ADVANCED LAYOUT RULE: choose visual "mind_map" for categories/benefits/types; "pros_cons_table" for pros vs cons or benefit vs drawback; "step_ladder" for level-up/growth/process stages; "flowchart_box" for cause -> effect chains; "before_after_box" for before/after transformation; "calendar_reminder" for date reminders; "ranked_list" for top priorities/order; "quote_card" for motivational or belief lines.',
    'PRESET RULE: when design/style is exam, prefer exam_date_card, calendar_reminder, document_checklist, timeline_strip. For career/business, prefer comparison_table, before_after_box, step_ladder, ranked_list. For motivation, prefer quote_card, effect_checkmark, highlight_swipe.',
    'Prefer 2.2-4.5 second beats. renderText max 7 words. renderBody max 10 words.',
    'AUDIO SYNC RULE: use timestampSegments when available. start/end must follow the exact spoken segment; do not create evenly spaced notes if transcript timestamps exist.',
    'SCENE VARIETY RULE: every 2-3 note actions, include one bigger structured moment when the script supports it: step_ladder, before_after_box, quote_card, document_checklist, timeline_strip, formula_box, comparison_table, exam_date_card, mind_map, pros_cons_table, or ranked_list. Do not make every item a plain bullet_write row.',
    'REEL RHYTHM RULE: target this flow when possible: page 1 big hook, page 2 step ladder/skill growth, page 3 warning or before-after mistake, page 4 quote/final checkmark. This keeps the reel from feeling like static lecture notes.',
    'AUDIO ENERGY RULE: use stronger visual tokens on stressed words or pauses. High-energy/spoken-problem moments -> punch-in + underline/red circle/X; solution/action moments -> checkmark/timeline; reflective final line -> quote_card.',
    'If there are multiple bullets, split them into separate videoUsePlan items with separate timings.',
    'ManagerChecklist before render: check whether text matches audio, requirements are followed, elements appear one-by-one, nothing important is missing, and the reel feels watchable for the user.',
    'Do not optimize for screen occupancy by adding filler. Clean white space is allowed. The priority is audio-text sync and clarity.',
    'If occupancy is below 60%, first increase note block scale or add one useful underline/revision box/arrow/sketch drawing tied to the current spoken point. Do not add unrelated future bullets or decorative badges.',
    'Use sketch drawings, arrows, diagrams, and highlights sparingly. They must support the exact spoken point, not decorate the screen.',
    `CONTROLLED DRAWING RULE: never ask for free AI drawing. In visual, use only safe tokens from this library: ${HANDWRITTEN_NOTES_VISUAL_TOKENS.join(', ')}.`,
    'Prefer Level 1/2 visuals: predefined doodles plus flowcharts, timelines, mind maps, arrows, boxes, highlights, and revision notes.',
    'Use Level 3 object sketches only if the concept cannot be explained by a controlled diagram.',
    'For every educational concept, extract cause-effect or process chains. Example: "RBI controls inflation" should become RBI -> Interest Rate -> Inflation, not only a sentence.',
    'If the script contains controls, leads to, after, because, selection, training, posting, apply, download, submit, deadline, exam date, admit card, mock test, result, career growth, skills, confidence, or rejection, create at least one diagram/timeline/timeline_strip/document_checklist/exam_date_card/step_ladder/before_after_box/quote_card note element.',
    'For images/icons/PNGs: request them only when they match the exact script moment. If missing or inaccurate, prefer clean text, box, flowchart, arrow, or controlled doodle.',
    'For sound: use writing tick sounds while text writes, soft pop sounds for highlights/checkmarks/X/circles, soft chime sounds for page transitions or final quote, and low background music/ambient bed that never fights the voiceover.',
    'Layouts should alternate hookCard, splitExplainer, checklistCard, statCard, warningCard, ctaCard according to note action.',
    'Use visual values like heading_write, bullet_write, diagram_flowchart, diagram_timeline, diagram_mindmap, formula_box, comparison_table, timeline_strip, document_checklist, exam_date_card, mind_map, pros_cons_table, step_ladder, flowchart_box, before_after_box, calendar_reminder, ranked_list, quote_card, effect_bracket, effect_checkmark, effect_xmark, arrow_diagram, highlight_swipe, red_circle, or a safe doodle token.',
  ];
}
