/**
 * Video Blueprint & Asset Fallback Specification Types for Long Video Pro
 *
 * Defines the structured output generated by the AI Visual Planning Agent.
 */

export type VisualType =
  | 'IMAGE'
  | 'VIDEO_CLIP'
  | 'FACE_PERSON'
  | 'TYPOGRAPHY'
  | 'CHART_GRAPH'
  | 'DIAGRAM_INFOGRAPHIC'
  | 'B_ROLL'
  | 'SIMPLE_BACKGROUND';

export type VisualPriority = 'HIGH' | 'MEDIUM' | 'LOW';
export type TextPriority = 'HIGH' | 'MEDIUM' | 'LOW';

export type VisualStylePreset =
  | 'cinematic_dark'
  | 'corporate_clean'
  | 'documentary_warm'
  | 'tech_futuristic';

export type AtmosphereBg =
  | 'abstract_dark'
  | 'tech_grid'
  | 'studio_bokeh'
  | 'warm_gradient'
  | 'none';

export type MotionAnimation =
  | 'slow_zoom_in'
  | 'slow_zoom_out'
  | 'pan_right'
  | 'pan_left'
  | 'scale_pop'
  | 'subtle_breathe'
  | 'none';

export type TransitionType =
  | 'hard_cut'
  | 'cross_dissolve'
  | 'soft_fade'
  | 'slide_left'
  | 'slide_right'
  | 'zoom_through';

export type PrimaryAssetSpec = {
  description: string;
  query: string;
  assetType: 'image' | 'video' | 'face' | 'chart' | 'none';
  requirement: string;
};

export type SecondaryAssetSpec = {
  description: string;
  query: string;
  assetType: 'image' | 'video' | 'background' | 'none';
  requirement: string;
};

export type FallbackVisualSpec = {
  type: 'typography' | 'chart' | 'simple_background';
  headline?: string;
  subtext?: string;
  statisticNumber?: string;
  statisticLabel?: string;
  backgroundColorHint?: string;
  keywordEmphasis?: string[];
};

export type BlueprintScene = {
  sceneNumber: number;
  startSeconds: number;
  endSeconds: number;
  durationSeconds: number;
  narrationText: string;
  visualType: VisualType;
  visualIntent: string;
  visualPriority: VisualPriority;
  
  primaryAsset: PrimaryAssetSpec;
  secondaryAsset: SecondaryAssetSpec;
  fallbackVisual: FallbackVisualSpec;

  onScreenText?: string;
  textPriority: TextPriority;
  
  chapterTitle?: string;
  speakerInfo?: {
    name: string;
    title?: string;
  };

  animation: MotionAnimation;
  transition: TransitionType;
  audioNote?: string;
  sfxCue?: string;
};

export type VideoBlueprint = {
  topicTitle: string;
  overallMood: string;
  estimatedDurationSeconds: number;
  totalScenes: number;
  scenes: BlueprintScene[];
  scriptSummary?: string;
  keyTakeaways?: string[];
  youtubeTimestamps?: string;
};

export type ResolvedSceneAsset = {
  resolvedUrl?: string;
  resolvedSource: 'primary' | 'secondary' | 'fallback';
  renderedType: VisualType;
  imageSrc?: string;
  videoSrc?: string;
  fallbackSpec: FallbackVisualSpec;
};

export type ResolvedBlueprintScene = BlueprintScene & ResolvedSceneAsset;
